### PR TITLE
Remove arm build of drone

### PR DESCRIPTION
**Pull request by guangbochen**
Remove harvester arm build since arm arch is currently not supported by kubevirt 
refer to: https://github.com/kubevirt/libvirt/issues/49
https://github.com/kubevirt/kubevirt/pull/3415

### CODE REVIEW

**Comment by orangedeng** [comment]
I think you need to remove arm64 build too.

**Review by orangedeng — CHANGES_REQUESTED** [review]
Need to remove arm64 build too

**Review by orangedeng — APPROVED** [review]
LGTM

**Comment by wonleing** [comment]
why we have to remove these code other than disable it somewhere?
I think kubevirt support arm64 is not far away.

**Pull request merged**
