### PR TITLE
Bump longhorn to v1.2.2-rc1

### PR DESCRIPTION
**Pull request by weihanglo**
Bump longhorn to v1.2.2-rc1

### CODE REVIEW

**Comment by weihanglo** [comment]
It would be great if we can ship Harvester v0.3.0 with a GA version of Longhorn instead of RC.

**Comment by FrankYang0529** [comment]
@weihanglo, I think we may need [longhorn-manager 1.2.2-rc1](https://github.com/longhorn/longhorn-manager/releases/tag/v1.2.2-rc1) to fix https://github.com/harvester/harvester/issues/945.

**Comment by joshimoo** [comment]
Definitively wait for a v1.2.2 sort of release, since currently restore behavior is broken on the v1.2.x release.
We are working on a fix as part of https://github.com/longhorn/longhorn/issues/3111 which is currently going through validation & regression testing

**Comment by guangbochen** [comment]
@weihanglo I reckon we can bump the LH to `v.1.2.2-rc1` with `helm package $chart_path` of https://github.com/longhorn/longhorn/tree/v1.2.2/chart and use the zip file generated from this command to facilitate the test before the official LH v1.2.2 release, thanks.

**Review by guangbochen — APPROVED** [review]
LGTM

**Pull request merged**
