### PR TITLE
Harvester-webhook uses same upgrade strategy as harvester

### PR DESCRIPTION
**Pull request by w13915984028**
**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

**Problem:**

The K8s default upgrade strategy is not fully fit for `harvester-webhook` deployment, instead it should keep the same strategy as `harvester` deployment.

**Solution:**

Update the deployment template.

**Related Issue:**

https://github.com/harvester/harvester/issues/6486
For reference: #6432 

**Test plan:**

1. Upgrade to the version, the `harvester-webhook` deployment has same `strategy` as `harvester` deployment.

2. On a single-node harvester cluster, edit the `harvester-webhook` deployment with a new image tag, the harvester-webhook pod will not be replaced at once, instead, you need to delete the current running pod manually to help the replaced POD to be running. After this patch, the POD will be replaced right now.

_

local test, a newly installed Harvester cluster.

```
 deployment -n harvester-system harvester-webhook -oyaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    helm.sh/resource-policy: keep
    management.cattle.io/scale-available: "3"
..
  creationTimestamp: "2024-09-03T15:59:18Z"
  generation: 1
..
  name: harvester-webhook
  namespace: harvester-system
..
spec:
  progressDeadlineSeconds: 600
  replicas: 1
..
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 2
    type: RollingUpdate
```

same as Harvester deployment:
```
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: apiserver
      app.kubernetes.io/name: harvester
      app.kubernetes.io/part-of: harvester
      helm.sh/release: harvester
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 2
    type: RollingUpdate
```

With the help of PR https://github.com/harvester/harvester-installer/pull/828 to get an ISO

### CODE REVIEW

**Comment by w13915984028** [comment]
@mergify backport v1.4

**Review by starbops — COMMENTED** [review]
One question: Given that this PR is applied, is it possible that a 2-node cluster has no harvester-webhook pods running at some specific time point?

What do you think about changing the maxUnavailable to 1? It's more conservative, and the rolling update process could be a bit slower, but it assures that at least one pod will be running at any given time.

**Comment by w13915984028** [comment]
> One question: Given that this PR is applied, is it possible that a 2-node cluster has no harvester-webhook pods running at some specific time point?
> 
> What do you think about changing the maxUnavailable to 1? It's more conservative, and the rolling update process could be a bit slower, but it assures that at least one pod will be running at any given time.

As per https://kubernetes.io/docs/concepts/workloads/controllers/deployment/

>For example, if you look at the above Deployment closely, you will see that it first creates a new Pod, then deletes an old Pod, and creates another new one. It does not kill old Pods until a sufficient number of new Pods have come up, and does not create new Pods until a sufficient number of old Pods have been killed.

K8s first creates a few new pods, then kill a few old pods, and rolling.

The original default `25% max unavailable, 25% max surge`, does not work well on 1-node or 2-node cluster, as it may not be able to create new one(s) first.

With new policy:
```
1-node cluster: create 1 new, delete 1 old
2-node cluster: create 2 new, delete 2 old
>=3-node cluster: create 2 new, delete 2 old, create 1 new, delete 1 old
```

```
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 2
```
and
```
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
```
will make slight differences. At the moment, would prefer to keep same strategy on `harvester` and `harvester-webhook`.

**Comment by starbops** [comment]
Besides the rolling update strategy, we need to take `podAntiAffinity` into account, too.

The default 25% `maxUnavailable` will be rounded down to zero if the deployment has only two replicas. With `podAntiAffinity` in place, the newly created pod cannot be scheduled if none of the old pods are deleted. Therefore, the rolling update procedure is jammed.

Suppose that `maxUnavailable` and `maxSurge` are both set to 2 and it is a 2-node cluster. When the rolling update starts, two new pods will be created but unschedulable to any node due to `podAntiAffinity`. Then, the two existing pods could be terminated simultaneously because `maxUnavailable` is 2. At that specific time point, there will be no harvester-webhook pods running.

I have concerns about the value here because harvester-webhook involves some core resources, e.g. Node. Though the downtime could be short in normal cases, its service disruption may impact the whole cluster, just like what we saw in #6461. We should do our best to minimize the risk.

**Comment by w13915984028** [comment]
I did a test on 2-node cluster.

Upgrade window:
```
$kubectl set image deploy harvester-webhook -n harvester-system harvester-webhook=rancher/harvester-webhook:fix6486-head && kubectl rollout status deploy harvester-webhook -n harvester-system

deployment.apps/harvester-webhook image updated
Waiting for deployment "harvester-webhook" rollout to finish: 0 of 2 updated replicas are available...
Waiting for deployment "harvester-webhook" rollout to finish: 1 of 2 updated replicas are available...
deployment "harvester-webhook" successfully rolled out
```

Observation window:
```
Fri Sep 20 12:51:33 UTC 2024
harvester-webhook-587d55bb5d-2t44q                      1/1     Running   0              5m11s
harvester-webhook-587d55bb5d-s4plv                      1/1     Running   0              5m11s

Fri Sep 20 12:51:33 UTC 2024
harvester-webhook-587d55bb5d-2t44q                      1/1     Terminating   0              5m12s
harvester-webhook-587d55bb5d-s4plv                      1/1     Terminating   0              5m12s
harvester-webhook-6cc47678bf-mmpf9                      0/1     Pending       0              1s
harvester-webhook-6cc47678bf-wrb2w                      0/1     Pending       0              1s

Fri Sep 20 12:51:34 UTC 2024
harvester-webhook-587d55bb5d-2t44q                      0/1     Terminating   0              5m12s
harvester-webhook-587d55bb5d-s4plv                      0/1     Terminating   0              5m12s
harvester-webhook-6cc47678bf-mmpf9                      0/1     Pending       0              1s
harvester-webhook-6cc47678bf-wrb2w                      0/1     Pending       0              1s

Fri Sep 20 12:51:34 UTC 2024
harvester-webhook-6cc47678bf-mmpf9                      0/1     Pending   0              2s
harvester-webhook-6cc47678bf-wrb2w                      0/1     Pending   0              2s

Fri Sep 20 12:51:35 UTC 2024
harvester-webhook-6cc47678bf-mmpf9                      0/1     ContainerCreating   0              2s
harvester-webhook-6cc47678bf-wrb2w                      0/1     ContainerCreating   0              2s

Fri Sep 20 12:51:35 UTC 2024
harvester-webhook-6cc47678bf-mmpf9                      0/1     ContainerCreating   0              2s
harvester-webhook-6cc47678bf-wrb2w                      0/1     ContainerCreating   0              2s
```

After change to
```
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
```

Upgrade window:
```
$ kubectl set image deploy harvester-webhook -n harvester-system harvester-webhook=rancher/harvester-webhook:fix6486-head && kubectl rollout status deploy harvester-webhook -n harvester-system

deployment.apps/harvester-webhook image updated
Waiting for deployment "harvester-webhook" rollout to finish: 1 out of 2 new replicas have been updated...
Waiting for deployment "harvester-webhook" rollout to finish: 1 out of 2 new replicas have been updated...
Waiting for deployment "harvester-webhook" rollout to finish: 1 old replicas are pending termination...
Waiting for deployment "harvester-webhook" rollout to finish: 1 old replicas are pending termination...
Waiting for deployment "harvester-webhook" rollout to finish: 1 old replicas are pending termination...
Waiting for deployment "harvester-webhook" rollout to finish: 1 of 2 updated replicas are available...
deployment "harvester-webhook" successfully rolled out
``` 

Observation window:
```
Fri Sep 20 13:01:53 UTC 2024
harvester-webhook-6cc47678bf-mmpf9                      1/1     Running   0              10m
harvester-webhook-6cc47678bf-wrb2w                      1/1     Running   0              10m

Fri Sep 20 13:01:54 UTC 2024
harvester-webhook-587d55bb5d-c2vfl                      0/1     Pending       0              0s
harvester-webhook-587d55bb5d-tjhlq                      0/1     Pending       0              0s
harvester-webhook-6cc47678bf-mmpf9                      1/1     Terminating   0              10m
harvester-webhook-6cc47678bf-wrb2w                      1/1     Running       0              10m

Fri Sep 20 13:01:54 UTC 2024
harvester-webhook-587d55bb5d-c2vfl                      0/1     Pending       0              0s
harvester-webhook-587d55bb5d-tjhlq                      0/1     Pending       0              0s
harvester-webhook-6cc47678bf-mmpf9                      0/1     Terminating   0              10m
harvester-webhook-6cc47678bf-wrb2w                      1/1     Running       0              10m

Fri Sep 20 13:01:55 UTC 2024
harvester-webhook-587d55bb5d-c2vfl                      0/1     Pending       0              1s
harvester-webhook-587d55bb5d-tjhlq                      0/1     Pending       0              1s
harvester-webhook-6cc47678bf-mmpf9                      0/1     Terminating   0              10m
harvester-webhook-6cc47678bf-wrb2w                      1/1     Running       0              10m

Fri Sep 20 13:01:55 UTC 2024
harvester-webhook-587d55bb5d-c2vfl                      0/1     Pending             0              1s
harvester-webhook-587d55bb5d-tjhlq                      0/1     ContainerCreating   0              1s
harvester-webhook-6cc47678bf-wrb2w                      1/1     Running             0              10m

Fri Sep 20 13:01:56 UTC 2024
harvester-webhook-587d55bb5d-c2vfl                      0/1     Pending             0              2s
harvester-webhook-587d55bb5d-tjhlq                      0/1     ContainerCreating   0              2s
harvester-webhook-6cc47678bf-wrb2w                      1/1     Running             0              10m

Fri Sep 20 13:01:56 UTC 2024
harvester-webhook-587d55bb5d-c2vfl                      0/1     Pending             0              2s
harvester-webhook-587d55bb5d-tjhlq                      0/1     ContainerCreating   0              2s
harvester-webhook-6cc47678bf-wrb2w                      1/1     Running             0              10m

Fri Sep 20 13:01:57 UTC 2024
harvester-webhook-587d55bb5d-c2vfl                      0/1     Pending             0              3s
harvester-webhook-587d55bb5d-tjhlq                      0/1     ContainerCreating   0              3s
harvester-webhook-6cc47678bf-wrb2w                      1/1     Running             0              10m

Fri Sep 20 13:01:57 UTC 2024
harvester-webhook-587d55bb5d-c2vfl                      0/1     Pending       0              3s
harvester-webhook-587d55bb5d-tjhlq                      1/1     Running       0              3s
harvester-webhook-6cc47678bf-wrb2w                      1/1     Terminating   0              10m

Fri Sep 20 13:01:58 UTC 2024
harvester-webhook-587d55bb5d-c2vfl                      0/1     ContainerCreating   0              4s
harvester-webhook-587d55bb5d-tjhlq                      1/1     Running             0              4s
harvester-webhook-6cc47678bf-wrb2w                      0/1     Terminating         0              10m

Fri Sep 20 13:01:58 UTC 2024
harvester-webhook-587d55bb5d-c2vfl                      0/1     ContainerCreating   0              4s
harvester-webhook-587d55bb5d-tjhlq                      1/1     Running             0              4s
harvester-webhook-6cc47678bf-wrb2w                      0/1     Terminating         0              10m

Fri Sep 20 13:01:59 UTC 2024
harvester-webhook-587d55bb5d-c2vfl                      1/1     Running   0              5s
harvester-webhook-587d55bb5d-tjhlq                      1/1     Running   0              5s
```

**Comment by w13915984028** [comment]
From the test, both `harvester` and `harvester` are better to follow below strategy, I will update the PR:

```
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
```

**Review by ibrokethecloud — APPROVED** [review]
lgtm. thanks.

**Review by bk201 — APPROVED** [review]

**Review by starbops — APPROVED** [review]
LGTM, thank you.

**Comment by w13915984028** [comment]
@mergify backport v1.3

**Pull request merged**
