### PR TITLE
Use node ip to update cert first and Close connection on cert changed

### PR DESCRIPTION
**Pull request by futuretea**
#268

## Problem
The dynamiclistener will `dynamically update` the certificate according to the change of the `listening address`. 
Because it is in the pod, if the pod's ip changes, the certificate will change. 

## Solution
* Close connection on cert changed
dynamiclistenner has a option `CloseConnOnCertChange`, after set it to true, if cert changed, connection  will  be closed，and let users trust the certificate again.
* Use node ip to update cert first
Here we fork the dynamiclistener. 
If the environment variable `NODE_IP` exists, the node's ip will be used first instead of the pod's ip.
`NODE_IP` can be mounted by：
```yaml
containers:
- env:
  - name: NODE_IP
    valueFrom:
      fieldRef:
         status.hostIP
```

### CODE REVIEW

**Comment by gitlawr** [comment]
How does this fix the problem? What if the pod moves to another node?

**Comment by futuretea** [comment]
> How does this fix the problem? What if the pod moves to another node?

If the pod drifts to another node, the same problem will still occur in Chrome

**Comment by futuretea** [comment]
> How does this fix the problem? What if the pod moves to another node?

Users need to refresh web page, and trust cert again

**Comment by guangbochen** [comment]
close in favor of https://github.com/rancher/harvester/pull/280

**Pull request closed without merging**
