### PR TITLE
Release v1.3.2

### PR DESCRIPTION
**Pull request by bk201**
Release v1.3.2

### CODE REVIEW

**Review by Vicente-Cheng — APPROVED** [review]
The changes LGTM, let's wait for the smoke result.

**Comment by bk201** [comment]
[test-results (1).zip](https://github.com/user-attachments/files/16898235/test-results.1.zip)

**Review by tserong — APPROVED** [review]

**Comment by tserong** [comment]
I checked the test results zip, three integration tests failed, and one errored.

I'm not sure about `test_create_vm_no_available_resources`, whether the test needs updating or something is actually broken (from the description the expected result is that the VM should be created successfully but is unschedulable, whereas it actually failed to create).

`test_update_vm_machine_type` should have been skipped (it says `@pytest.mark.skip_version_if("> v1.2.1", "> v1.3.0", ...`) but instead failed twice.

`test_vm_with_bogus_vlan` errored, but possibly the test needs updating to match the 500 return code?

**Comment by bk201** [comment]
Just re-run the individual tests and it looks OK, might be flaky faulure:
```
harvester_e2e_tests/integrations/test_3_vm_functions.py::test_create_vm_no_available_resources[cpu] PASSED                                                                            [ 20%]
harvester_e2e_tests/integrations/test_3_vm_functions.py::test_create_vm_no_available_resources[mem] PASSED                                                                            [ 40%]
harvester_e2e_tests/integrations/test_3_vm_functions.py::test_create_vm_no_available_resources[disk] PASSED                                                                           [ 60%]
harvester_e2e_tests/integrations/test_3_vm_functions.py::test_create_vm_no_available_resources[mem-and-cpu] PASSED                                                                    [ 80%]
harvester_e2e_tests/integrations/test_3_vm_functions.py::test_create_vm_no_available_resources[mem-cpu-and-disk] PASSED                                                               [100%]
```

**Pull request merged**
