### PR TITLE
Bump harvester network controller and harvester load balancer images

### PR DESCRIPTION
**Pull request by yaocw2020**
**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

**Problem:**

**Solution:** Bump harvester network controller and harvester load balancer images

**Related Issue:** 

**Test plan:**

### CODE REVIEW

**Review by guangbochen — APPROVED** [review]
LGTM, thanks.

**Review by futuretea — COMMENTED** [review]
missing charts pkgs

**Comment by yaocw2020** [comment]
> missing charts pkgs

The charts are not changed.

**Review by futuretea — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
