### PR TITLE
bump: kubevirt to v1.1.1

### PR DESCRIPTION
**Pull request by Yu-Jack**
**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

**Problem:**
Although v1.1.0 supports [USB Host Passthrough](https://kubevirt.io/user-guide/virtual_machines/host-devices/#usb-host-passthrough), but there is a [permission issue](https://github.com/kubevirt/kubevirt/pull/10753) fixed on v1.1.1.

**Solution:**
Upgrade kubevirt to v1.1.1 firstly. 

Although we have another issue https://github.com/harvester/harvester/issues/5083 will upgrade kubevirt to v1.2.0, but I think we could upgrade gradually, it would be more easier.

**Related Issue:**
https://github.com/harvester/harvester/issues/1710

**Test plan:**

- [x] Start VM
- [x] Start VM with [USB Passthrough](https://kubevirt.io/user-guide/virtual_machines/host-devices/#usb-host-passthrough), it's enough to use official setting to test this feature.

This PR is focusing bump kubevirt, there would be another design PR regarding the USB passthrough.

### CODE REVIEW

**Comment by bk201** [comment]
@Yu-Jack Should we bump KubeVirt images too? https://github.com/harvester/harvester/blob/2eb05d368fff3f6ab783112159c58fdc64c6896e/deploy/charts/harvester/values.yaml#L29

**Comment by Yu-Jack** [comment]
@bk201 yes, we need to bump that as well, but how do I get the correct version from `registry.suse.com/suse/sles/15.5/virt-operator`?

**Comment by bk201** [comment]
> @bk201 yes, we need to bump that as well, but how do I get the correct version from `registry.suse.com/suse/sles/15.5/virt-operator`?

I'll share how to get a supported suse image with you offline.

**Comment by Yu-Jack** [comment]
> @Yu-Jack Should we bump KubeVirt images too?
> 
> https://github.com/harvester/harvester/blob/2eb05d368fff3f6ab783112159c58fdc64c6896e/deploy/charts/harvester/values.yaml#L29

sure, I'll bump that later.

**Comment by Yu-Jack** [comment]
Currently, there is a bug in `1.1.1-150500.8.9.1`, so I'll update new tag after that bug being resolved.

**Comment by Yu-Jack** [comment]
Upgrade kubevirtVersion  to `1.1.1-150500.8.12.1`, and it works.

**Review by FrankYang0529 — APPROVED** [review]
LGTM. Basic operations like creating and migrating VM can work.

**Review by Vicente-Cheng — APPROVED** [review]
LGTM, upgrade from v1.2.1 to this PR works.

All VM basic operations also look fine.

**Review by bk201 — APPROVED** [review]
lgtm!

**Review by FrankYang0529 — APPROVED** [review]
LGTM. Thanks.

**Comment by Vicente-Cheng** [comment]
@mergifyio backport v1.2

**Comment by Vicente-Cheng** [comment]
@mergifyio backport v1.3

**Pull request merged**
