### PR TITLE
feat: bump longhorn to v1.6.0

### PR DESCRIPTION
**Pull request by FrankYang0529**
**Solution:**
Bump LH to v1.6.0.

**Related Issue:**
https://github.com/harvester/harvester/issues/4970

**Test plan:**

### Case 1: New cluster

Make sure users can operate creating/migrating VM, creating and restoring VMBackup/VMSnapshot.

### Case 2: Upgrade cluster

1. Create a harvester v1.2.1 cluster.
2. Create a guest cluster.
3. Make sure the harvester can bump to this branch.

### CODE REVIEW

**Review by bk201 — APPROVED** [review]

**Review by WebberHuang1118 — APPROVED** [review]
Checked with fundamental operations: (data integrity verification included if needed)

Prerequisites:
- Build Harvester Cluster with v1.2.1
- Upload image `img`
- Creating VM `vm` from image `img`, and writing some data
- Creating VM backup `vm-b0` from VM `vm`
- Creating VM snapshot `vm-s0` from VM `vm`

Steps:
- Upgrading Harvester to this branch
- Restoring VM from VM backup `vm-b0`
- Restoring VM from VM snapshot `vm-s0`
- Creating a new VM backup `vm-b1`
- Restoring VM from VM backup `vm-b1` as `New`
- Restoring VM from VM backup `vm-b1` as `New` to another namespace
- Restoring VM from VM backup `vm-b1` as `Existing`
- Creating a new VM with image `img`
- Uploading new image `img-new`, and creating a new VM with this image
- Exporting any existing VM rootfs volume as an image, and creating a new VM with the exported image

Above operations all works as expected, LGTM, thanks.

**Comment by innobead** [comment]
Thanks, everyone. 

@khushboo-rancher @lanfon72 do we have an automated sanity test for the Longhorn version upgrade? If not, consider having it in the future, so we can leverage it to verify what members tested here to make everything more productive.

**Review by Vicente-Cheng — APPROVED** [review]
LGTM, tested with https://github.com/harvester/harvester/pull/5105
upgrade path from v1.2.1 -> v1.2-head (with Longhorn v1.5.3) -> master-head (with this PR)

verified the VM can be migrated (w/o vlan due to https://github.com/harvester/harvester/issues/5076)
And all basic operations work well.

Also tested the snapshot/backup/restore work well.

**Comment by lanfon72** [comment]
> Thanks, everyone.
> 
> @khushboo-rancher @lanfon72 do we have an automated sanity test for the Longhorn version upgrade? If not, consider having it in the future, so we can leverage it to verify what members tested here to make everything more productive.

We don't have any sanity tests to test Longhorn specific functionality yet, let's add this to our TODO items.

**Pull request merged**
