### PR TITLE
upgrade: add debug parameter for elemental upgrade

### PR DESCRIPTION
**Pull request by Vicente-Cheng**
**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

**Problem:**
Try to get more logs when we use the elemental command.

**Solution:**
Add debug parameter.

**Related Issue:**
https://github.com/harvester/harvester/issues/4541

**Test plan:**
make sure the upgrade works as usual

### CODE REVIEW

**Review by guangbochen — APPROVED** [review]
LGTM, thanks.

**Review by bk201 — APPROVED** [review]
LGTM, debug log is included.

**Review by starbops — APPROVED** [review]
LGTM, thanks!

**Comment by bk201** [comment]
@mergifyio backport v1.2

**Comment by Vicente-Cheng** [comment]
@Mergifyio backport v1.1

**Pull request merged**
