### PR TITLE
Bump kubevip to v0.5.10

### PR DESCRIPTION
**Pull request by yaocw2020**
**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

**Problem:**

There are some CVEs in the old version. 

**Solution:**

Bump to the latest version.

We won't bump kube-vip-cloud-provider because 
- The kube-vip-cloud-provider latest version is incompatible with the version we use currently.
- We will disable the kube-vip-cloud-provider in the Harvester v1.2.0. 

**Related Issue:**
https://github.com/harvester/security/issues/19

**Test plan:**

Regress the LB test cases of Harvester including the DHCP and IPAM modes. Detailly,
- Set up a Harvester cluster and create an RKE2 downstream cluster with the Harvester cloud provider.
- Set the VIP pool where IPs can be reachable.
- Deploy an Nginx and create the related laodbalancer type services including both DHCP and IPAM mode.
- Ping LB address.

### CODE REVIEW

**Review by guangbochen — COMMENTED** [review]
can we add proper test plans and explain why not choose to bump the vip-cloud-provider

**Comment by yaocw2020** [comment]
> can we add proper test plans and explain why not choose to bump the vip-cloud-provider

Yes, done, thank you for the reminding.

**Review by chrisho — APPROVED** [review]
LGTM, thanks.

**Review by bk201 — APPROVED** [review]

**Review by guangbochen — APPROVED** [review]
LGTM and verifed that the LB feature works as expected on the guest k8s cluster with v0.5.10 kube-vip.
image

**Comment by guangbochen** [comment]
@mergify backport v1.1

**Pull request merged**
