### PR TITLE
fix(upgradelog): unset log-processing return value

### PR DESCRIPTION
**Pull request by starbops**
**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

**Problem:**

When there's an error happened to process the log lines, every log file after the problematic log file (lexical order) will be mistakenly skipped.

**Solution:**

Reset the return value variable at the end of each run.

**Related Issue:**

#3705

**Test plan:**

1. Provision a single-node Harvester cluster with an ISO image including the fix
2. Trigger an upgrade to the same version using the same ISO image
3. `kubectl exec` into the fluentd Pod and mess up a random log file, for example, `echo "AA AA AA" >> /archive/logs/harvester-system.harvester-86bfd6897c-gjqtr.apiserver.20230323.log`
4. Click "Download Log" on the UI
5. Check the downloaded log archive, the only file in JSON format should be the file you messed up with, other files should be normal

### CODE REVIEW

**Review by w13915984028 — COMMENTED** [review]
regarding https://man7.org/linux/man-pages/man1/unset.1p.html

```
       If neither -f nor -v is specified, name refers to a variable; if
       a variable by that name does not exist, it is unspecified whether
       a function by that name, if any, shall be unset.
```

the better solution will be:
```
ret=0 # declare var first, as the code is not put under a function, the `local` will not work
for...
do
  .... || ret=$?
  if ret != 0
  ...
  ret=0 # set back to 0
done
```

but for here, a simple nested shell code, the `unset` also works.

**Review by w13915984028 — APPROVED** [review]
LGTM, thanks.

**Review by bk201 — APPROVED** [review]

**Comment by bk201** [comment]
@mergifyio backport v1..1

**Comment by bk201** [comment]
@mergifyio backport v1.1

**Pull request merged**
