### PR TITLE
Release v1.1.2-rc8

### PR DESCRIPTION
**Pull request by bk201**
Deps:
- GUI: v1.1.2-rc8
- Installer:v1.1.2-rc8
- network controller: 0.3.2-rc5

The commits include backport of https://github.com/harvester/harvester/pull/3787

### CODE REVIEW

**Review by Vicente-Cheng — APPROVED** [review]
LGTM!

**Review by futuretea — APPROVED** [review]
LGTM

**Comment by futuretea** [comment]
create a new single node cluster, work fine
image
image

**Comment by futuretea** [comment]
upgrade v1.1.1->v1.1-head work
image

**Comment by Vicente-Cheng** [comment]
Upgrade from v1.1.1 -> v1.1-head and basic operations look well.
Also, the downstream cluster is created then PVC works.

**Pull request merged**
