### PR TITLE
upgrade: update the elemental-cli repo

### PR DESCRIPTION
**Pull request by Vicente-Cheng**
**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

**Problem:**
We use the internal repo that made CI fail because the repo is not alive anymore.

**Solution:**
Try to use the correct repo for elemental-cli

**Related Issue:**
None

**Test plan:**
Check the CI result.

### CODE REVIEW

**Review by starbops — APPROVED** [review]
LGTM, thanks!

Tested by directly calling the downloaded `elemental` binary with v1.2.0's rootfs can successfully upgrade the Harvester OS.

Before the upgrade:

```
$ cat /etc/os-release 
NAME="SLE Micro"
VERSION="5.3"
VERSION_ID="5.3"
PRETTY_NAME="Harvester v1.1.2"
ID="sle-micro-rancher"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sle-micro-rancher:5.3"
VARIANT="Harvester"
VARIANT_ID="Harvester-20230420"
GRUB_ENTRY_NAME="Harvester v1.1.2"

$ uname
Linux elemental-test 5.14.21-150400.24.60-default #1 SMP PREEMPT_DYNAMIC Wed Apr 12 12:13:32 UTC 2023 (93dbe2e) x86_64 x86_64 x86_64 GNU/Linux
```

After elemental upgrade and node reboot:

```
$ cat /etc/os-release 
NAME="SLE Micro"
VERSION="5.3"
VERSION_ID="5.3"
PRETTY_NAME="Harvester v1.2.0"
ID="sle-micro-rancher"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sle-micro-rancher:5.3"
VARIANT="Harvester"
VARIANT_ID="Harvester-v1.2-20230907"
GRUB_ENTRY_NAME="Harvester v1.2.0"

$ uname
Linux harvester-fbczw 5.14.21-150400.24.81-default #1 SMP PREEMPT_DYNAMIC Tue Aug 8 14:10:43 UTC 2023 (90a74a8) x86_64 x86_64 x86_64 GNU/Linux
```

**Review by bk201 — APPROVED** [review]
lgtm, thanks!

**Comment by bk201** [comment]
@mergifyio backport v1.2

**Comment by Vicente-Cheng** [comment]
@mergifyio backport v1.1

**Pull request merged**
