### PR TITLE
feat2517 harvester support alertmanager

### PR DESCRIPTION
**Pull request by w13915984028**
Signed-off-by: Jian Wang <w13915984028@gmail.com>
```
Longhorn alert is available
  Add Longhorn ServiceMonitor and PrometheusRule, prometheus will grab data from Longhorn and fire the defined alert

KubeVirt alert is available
  KubeVirt existing alert has an issue of VirtOperatorDown, which is solved in deployment.yaml and kubevirt-operator-0.1.0.tgz
```
**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

**Problem:**

Harvester support alertmanager.

**Solution:**

1. Add longhorn related prometheus config, that will generate statistics and alarms
2. Fix kubevirtoperatordown issue

**Related Issue:**
https://github.com/harvester/harvester/issues/2517
https://github.com/harvester/harvester/issues/2520
https://github.com/harvester/harvester/issues/2615

HEP:
https://github.com/w13915984028/harvester/blob/fix2517/enhancements/20220720-alertmanager.md

**Test plan:**

Per HEP

The Code PR in Harvester-installer:
https://github.com/harvester/harvester-installer/pull/322

HEP PR:  https://github.com/harvester/harvester/pull/2545

### CODE REVIEW

**Comment by bk201** [comment]
@w13915984028 The PR works, it would be nice to briefly include what's changed in the commit messages or separate changes to multiple commits since the PR fixes several issues.

**Comment by w13915984028** [comment]
@bk201 : updated the commit message and PR description, thanks.

**Review by guangbochen — APPROVED** [review]
LGTM, thanks.

**Review by bk201 — APPROVED** [review]
LGTM, thanks for updating the commit messages.

**Comment by richard-cox** [comment]
@w13915984028 This seems to have broken the instructions over at https://docs.harvesterhci.io/v1.0/dev/dev-mode/ 

```
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: [resource mapping not found for name: "prometheus-longhorn-rules" namespace: "longhorn-system" from "": no matches for kind "PrometheusRule" in version "monitoring.coreos.com/v1"
ensure CRDs are installed first, resource mapping not found for name: "longhorn-prometheus-servicemonitor" namespace: "longhorn-system" from "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
ensure CRDs are installed first]
```

Going back to the previous commit in `harvester/harvester` worked fine. 

Are there any pending updates to those docs or fixes that can be applied locally to get the latest harvester up and running?

**Comment by w13915984028** [comment]
@richard-cox I will check. 

The current code assumes that the `rancher-monitoring` has already been deployed, then it's `harvester's turn. In `dev-mode`, `rancher-monitoring` is no there, that's why it complains  
```no matches for kind "PrometheusRule" / "ServiceMonitor" ```

**Pull request merged**
