### PR TITLE
Bump Longhorn dependency to v1.3.1

### PR DESCRIPTION
**Pull request by guangbochen**
**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

**Problem:**
Need to bump Longhorn dependency to the latest v1.3.1 release.

**Solution:**
Bump Longhorn dependency to v1.3.1

**Related Issue:**
https://github.com/harvester/harvester/issues/2404
https://github.com/harvester/harvester/issues/2315

**Test plan:**

### CODE REVIEW

**Comment by bk201** [comment]
Volume attaching looks OK to me.

**Comment by guangbochen** [comment]
Rebased and verified again in the new env, it works correctly of image upload and VM creation, thanks.

**Review by bk201 — APPROVED** [review]
LGTM

**Review by FrankYang0529 — APPROVED** [review]
Test and functions work as expected. LGTM. Thanks.

**Pull request merged**
