### PR TITLE
Bump node-manager chart to v0.2.3 (Helm)

### PR DESCRIPTION
**Pull request by connorkuehl**
Packaging changes:

* c48f3ac node-manager: Bump to v0.2.3
* 9854512 node-manager-webhook: Use node-manager tolerations
* 75a9b01 node-manager-webhook: Defer replica scaling to scale-available annotation

No application changes.

**Related Issues:**

* https://github.com/harvester/harvester/issues/5210
* https://github.com/harvester/harvester/issues/5212

```diff
diff -Naur harvester-node-manager-0.2.2/Chart.yaml harvester-node-manager-0.2.3/Chart.yaml
--- harvester-node-manager-0.2.2/Chart.yaml	2024-02-16 04:41:26.000000000 -0600
+++ harvester-node-manager-0.2.3/Chart.yaml	2024-02-27 14:03:12.000000000 -0600
@@ -5,4 +5,4 @@
 - name: harvester
 name: harvester-node-manager
 type: application
-version: 0.2.2
+version: 0.2.3
diff -Naur harvester-node-manager-0.2.2/templates/deployment.yaml harvester-node-manager-0.2.3/templates/deployment.yaml
--- harvester-node-manager-0.2.2/templates/deployment.yaml	2024-02-16 04:41:26.000000000 -0600
+++ harvester-node-manager-0.2.3/templates/deployment.yaml	2024-02-27 14:03:12.000000000 -0600
@@ -14,7 +14,9 @@
   selector:
     matchLabels:
       {{- include "harvester-node-manager-webhook.selectorLabels" . | nindent 6 }}
+  {{- if not .Values.webhook.replicas }}
   replicas: {{ .Values.webhook.replicas }}
+  {{- end }}
   template:
     metadata:
       labels:
@@ -33,4 +35,8 @@
             - name: WEBHOOK_SERVER_HTTPS_PORT
               value: "8443"
             - name: NAMESPACE
-              value: {{ .Release.Namespace }}
\ No newline at end of file
+              value: {{ .Release.Namespace }}
+      {{- with .Values.tolerations }}
+      tolerations:
+        {{- toYaml . | nindent 8 }}
+      {{- end }}
\ No newline at end of file
```

### CODE REVIEW

**Comment by connorkuehl** [comment]
Not sure I managed the Chart.lock file properly.

I updated the node-manager chart version in Chart.yaml, then ran `helm dependency update`, but that also seemed to have pulled down new tarballs for all of the other dependencies.

To produce this PR, I only checked in the changes to Chart.lock, Chart.yaml, and the harvester-node-manager tarball.

Not sure if that's incorrect. I looked around to see if there's a `helm dependency update` for just 1 dependency, but was not turning up any results.

In any case, initial testing from an ISO built from this branch seems correct.

**Comment by bk201** [comment]
> Not sure I managed the Chart.lock file properly.
> 
> I updated the node-manager chart version in Chart.yaml, then ran `helm dependency update`, but that also seemed to have pulled down new tarballs for all of the other dependencies.
> 
> To produce this PR, I only checked in the changes to Chart.lock, Chart.yaml, and the harvester-node-manager tarball.
> 
> Not sure if that's incorrect. I looked around to see if there's a `helm dependency update` for just 1 dependency, but was not turning up any results.
> 
> In any case, initial testing from an ISO built from this branch seems correct.

This is exactly how we did. We skip those tarballs (which have no content change but only timestamps).

**Review by bk201 — APPROVED** [review]

**Review by Vicente-Cheng — APPROVED** [review]
lgtm, thanks!

**Comment by bk201** [comment]
@mergifyio backport v1.3

**Comment by connorkuehl** [comment]
> This is exactly how we did. We skip those tarballs (which have no content change but only timestamps).

Thank you for clarifying! :slightly_smiling_face:

**Pull request merged**
