### PR TITLE
feat: support image HA (harvester#5897) 

### PR DESCRIPTION
**Pull request by WebberHuang1118**
**Problem:**
Support VM image HA

**Solution:**
Use sc parameter replica number for backing image HA copy number

**Related Issue:**
#5897 

**Test plan:**
- Creating a two-node Harvester with the master-head branch
- Updating Harvester deployment with this PR
- Creating a sc with `numberOfReplicas` as 1, and make it the default sc
- Creating a VM image
- Preparing a script `compare_bi_disk.sh` with the following content, this will check the image existence
  ```
  #!/bin/bash
  
  # Check if backing image name is provided
  if [ "$#" -ne 1 ]; then
      echo "Usage: $0 <backing-image-name>"
      exit 1
  fi
  
  backing_image_name="$1"
  
  # Fetch all node names in longhorn-system namespace
  node_names=$(kubectl get nodes.longhorn.io -n longhorn-system -o jsonpath='{.items[*].metadata.name}')
  
  # Fetch disk file status map keys from BackingImage
  backingimage_keys=$(kubectl get backingimages.longhorn.io $backing_image_name -n longhorn-system -o jsonpath='{.status.diskFileStatusMap}' | jq -r 'keys[]')
  
  # Loop over each node
  for node in $node_names; do
    #echo "Checking node: $node"
    # Fetch diskUUIDs from current node
    node_disk_uuids=$(kubectl get nodes.longhorn.io $node -n longhorn-system -o jsonpath='{.status.diskStatus.*.diskUUID}')
    
    # Compare each diskUUID from current node with backing image keys
    for uuid in $node_disk_uuids; do
      for key in $backingimage_keys; do
        #echo "Checking UUID: $uuid against Key: $key"
        if [[ "$uuid" == "$key" ]]; then
          echo "Match found on Node $node: $uuid"
        fi
      done
    done
  done
  ```
- Run `compare_bi_disk.sh <bi name>`
- Getting image only exists on one disk, for example:
  ```
  $ ./compare_bi_disk.sh vmi-99e9485c-96b7-4f9c-819f-66b545936823
  Match found on Node harvester-node-0: b17b4d1a-e983-4adc-be2b-2ff8e1f0b488
  ```
- Using LH GUI to edit the match disk as `allowScheduling: false` and `evictionRequested: true`
- Wait a while, and run `compare_bi_disk.sh <bi name>` again, the image will migrate to another disk
  ```
  $ ./compare_bi_disk.sh vmi-99e9485c-96b7-4f9c-819f-66b545936823
  Match found on Node harvester-node-1: c4fb1e0a-5022-4c21-8344-4a231bfed323
  ```
- Using LH GUI to enable the disk back (as `allowScheduling: true` and `evictionRequested: false`)
- Editing bi's `spec.minNumberOfCopies` as 2
- Waiting a while, and run `compare_bi_disk.sh <bi name>` , the image will exist on both nodes
  ```
  $ ./compare_bi_disk.sh vmi-99e9485c-96b7-4f9c-819f-66b545936823
  Match found on Node harvester-node-0: b17b4d1a-e983-4adc-be2b-2ff8e1f0b488
  Match found on Node harvester-node-1: c4fb1e0a-5022-4c21-8344-4a231bfed323
  ```
- Editing bi's `spec.minNumberOfCopies` back to 1
- Editing LH setting `backing-image-cleanup-wait-interval` as 1 (one minute)
- After about one minute, the image will only exist on one node
  ```
  $ ./compare_bi_disk.sh vmi-99e9485c-96b7-4f9c-819f-66b545936823
  Match found on Node harvester-node-1: c4fb1e0a-5022-4c21-8344-4a231bfed323
  ```

### CODE REVIEW

**Comment by FrankYang0529** [comment]
Hi @WebberHuang1118, just curious, what happen if we use `numberOfReplicas` more than node count? Will the BackingImage be ready?

**Comment by WebberHuang1118** [comment]
> Hi @WebberHuang1118, just curious, what happen if we use `numberOfReplicas` more than node count? Will the BackingImage be ready?

Hi @FrankYang0529,
the backing image still could be created, but the LH manager's log will be flooded with https://github.com/longhorn/longhorn-manager/blob/65bbe0b497847738f4dc3a2f2caebdbfa0952d41/controller/backing_image_controller.go#L368

**Review by bk201 — APPROVED** [review]

**Review by FrankYang0529 — APPROVED** [review]
LGTM. Thanks.

**Comment by FrankYang0529** [comment]
@mergify backport v1.4

**Pull request merged**
