### PR TITLE
feat: bump kubevirt to 1.1.1-150500.8.18.1

### PR DESCRIPTION
**Pull request by FrankYang0529**
**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

**Problem:**

**Solution:**

**Related Issue:**
https://github.com/harvester/harvester/issues/6131

**Test plan:**

Create / Migrate VM should work.

### CODE REVIEW

**Review by Yu-Jack — APPROVED** [review]

**Comment by bk201** [comment]
I keep getting an error on this e2e test, please see if you have some insight into it:

<details>
<summary> TestHotPlugVolume.test_add </summary>

```
    @pytest.fixture(scope="class")
    def stopped_vm(api_client, ssh_keypair, wait_timeout, image, unique_vm_name):
        unique_vm_name = f"stopped-{datetime.now().strftime('%m%S%f')}-{unique_vm_name}"
        cpu, mem = 1, 2
        pub_key, pri_key = ssh_keypair
        vm_spec = api_client.vms.Spec(cpu, mem)
        vm_spec.add_image("disk-0", image['id'])
        vm_spec.run_strategy = "Halted"

        userdata = yaml.safe_load(vm_spec.user_data)
        userdata['ssh_authorized_keys'] = [pub_key]
        vm_spec.user_data = yaml.dump(userdata)

        code, data = api_client.vms.create(unique_vm_name, vm_spec)
        endtime = datetime.now() + timedelta(seconds=wait_timeout)
        while endtime > datetime.now():
            code, data = api_client.vms.get(unique_vm_name)
            if "Stopped" == data.get('status', {}).get('printableStatus'):
                break
            sleep(1)

        yield unique_vm_name, image['user']

        code, data = api_client.vms.get(unique_vm_name)
        vm_spec = api_client.vms.Spec.from_dict(data)

        api_client.vms.delete(unique_vm_name)
        endtime = datetime.now() + timedelta(seconds=wait_timeout)
        while endtime > datetime.now():
            code, data = api_client.vms.get_status(unique_vm_name)
            if 404 == code:
                break
            sleep(3)

        for vol in vm_spec.volumes:
>           vol_name = vol['volume']['persistentVolumeClaim']['claimName']
E           KeyError: 'persistentVolumeClaim'

harvester_e2e_tests/integrations/test_3_vm_functions.py:155: KeyError
```

</details>

Not entirely sure if it's due to a nested environment. cc @lanfon72 too.

**Comment by FrankYang0529** [comment]
> I keep getting an error on this e2e test, please see if you have some insight into it:
> 
> TestHotPlugVolume.test_add

I can't manually reproduce the issue. The `KeyError` is more like missing key in the map, not server error.

**Review by bk201 — APPROVED** [review]
e2e test passed after using my local machine.

**Comment by bk201** [comment]
@mergifyio backport v1.3 v1.2

**Pull request merged**
