### PR TITLE
Bump harvester load balancer 0.2.0-rc2

### PR DESCRIPTION
**Pull request by yaocw2020**
**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

**Problem:**

**Solution:**

**Related Issue:** https://github.com/harvester/harvester/issues/4000

**Test plan:**

### CODE REVIEW

**Review by futuretea — APPROVED** [review]
LGTM, thanks.

**Review by guangbochen — APPROVED** [review]
LGMT, thanks.

**Comment by guangbochen** [comment]
@yaocw2020 can u please help to backport this manually to the v1.2 branch, we need to update the [tag image](https://github.com/harvester/harvester/blob/v1.2/deploy/charts/harvester/values.yaml#L456-L461) as well, thanks.

**Comment by yaocw2020** [comment]
@mergify backport v1.2

**Pull request merged**
