### PR TITLE
Prepare Harvester v1.2.0-rc1 release

### PR DESCRIPTION
**Pull request by guangbochen**
**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

**Problem:**
Prepare Harvester v1.2.0-rc1 release

**Solution:**
Bump dependency chart tag & imagePullPolicy, and update the `v1.2` branch tags

### CODE REVIEW

**Comment by bk201** [comment]
Need to add upgrade-matrix.yaml e.g: https://github.com/harvester/harvester/pull/3752/files#diff-7396abf878323d0aa188c59ee342f7d42b0025b29f7b4c797e70fae399bc81bf

**Review by bk201 — APPROVED** [review]
lgtm.

**Review by Vicente-Cheng — APPROVED** [review]
Upgrade tested. Basic operations also look well.
Creating downstream cluster and PVC is ok.
LGTM, Thanks!

**Review by futuretea — APPROVED** [review]
LGTM, tested a new cluster:
- pod status
- create vm
- create backup
- restore backup
- create snapshot
- restore snapshot
- create image
- upload image
- create network
- create cluster network/vlanconfig

**Pull request merged**
