### PR TITLE
Bump node-manager chart to v0.2.2 (Helm)

### PR DESCRIPTION
**Pull request by connorkuehl**
Application changes:

* 0e0dadd Require CloudInit .spec.contents to be valid YAML

Packaging changes:

* 0026aea node-manager: Bump to v0.2.2
* 70ef708 Use scale-available annotation for node-manager webhook
* 38b9619 node-manager: bump to v0.2.1
* ed7b0d9 node-manager: use .Chart.AppVersion as default value for webhook tag

**Related Issue:**

* https://github.com/harvester/harvester/issues/5119
* https://github.com/harvester/harvester/issues/5149

**Test plan:**

### CODE REVIEW

**Comment by connorkuehl** [comment]
```diff
--- harvester-node-manager-0.2.0/Chart.yaml	2024-01-25 01:20:31.000000000 -0600
+++ harvester-node-manager-0.2.2/Chart.yaml	2024-02-16 04:41:26.000000000 -0600
@@ -1,8 +1,8 @@
 apiVersion: v2
-appVersion: v0.2.0
+appVersion: v0.2.1
 description: A Helm chart for Harvester Node Manager
 maintainers:
 - name: harvester
 name: harvester-node-manager
 type: application
-version: 0.2.0
+version: 0.2.2
diff -Naur harvester-node-manager-0.2.0/templates/deployment.yaml harvester-node-manager-0.2.2/templates/deployment.yaml
--- harvester-node-manager-0.2.0/templates/deployment.yaml	2024-01-25 01:20:31.000000000 -0600
+++ harvester-node-manager-0.2.2/templates/deployment.yaml	2024-02-16 04:41:26.000000000 -0600
@@ -6,6 +6,10 @@
   namespace: {{ .Release.Namespace }}
   labels:
     {{- include "harvester-node-manager-webhook.labels" . | nindent 4 }}
+  {{- with .Values.webhook.replicas }}
+  annotations:
+    management.cattle.io/scale-available: "{{ . }}"
+  {{- end }}
 spec:
   selector:
     matchLabels:
@@ -19,7 +23,7 @@
       serviceAccountName: {{ include "harvester-node-manager-webhook.name" . }}
       containers:
         - name: harvester-node-manager-webhook
-          image: "{{ .Values.webhook.image.repository}}:{{ .Values.webhook.image.tag }}"
+          image: "{{ .Values.webhook.image.repository}}:{{ .Values.webhook.image.tag | default .Chart.AppVersion }}"
           imagePullPolicy: {{ .Values.webhook.image.pullPolicy }}
           ports:
           - containerPort: 8443
```

**Comment by bk201** [comment]
@connorkuehl I bump the chart in master: https://github.com/harvester/harvester/pull/5162
And update the image tag in the 1.3 branch (this PR).
I also run `helm dependency update` to update the Chart.lock file.

**Review by Vicente-Cheng — APPROVED** [review]
LGTM, thanks!

**Review by ibrokethecloud — APPROVED** [review]
lgtm. thanks.

**Pull request merged**
