### PR TITLE
HEP: vlan enhance

### PR DESCRIPTION
**Pull request by tjjh89017**
**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

**Problem:**

IT usually configures the switch with VLAN trunk mode rather than VLAN access mode or hybrid mode in a production environment. Therefore, we should add VLAN support for harvester-mgmt and allow multiple Linux bridges in Harvester node configuration.

preview page: https://github.com/tjjh89017/harvester/blob/vlan_enhance/enhancements/20220418-vlan-enhancement.md

**Solution:**

**Related Issue:**
https://github.com/harvester/harvester/issues/1390

**Test plan:**

### CODE REVIEW

**Review by guangbochen — COMMENTED** [review]
Thanks for the HEP documentation, here's some personal feedback:
1. Can u please add the relevant modifications to the Network CRD YAML file?
1. Can you describe the changes involved in the upgrade first (maybe a solution will be added later)?
1. For network diagrams, prefer to change the `Not Possible` to `Not Support`

**Comment by tjjh89017** [comment]
> Thanks for the HEP documentation, here's some personal feedback:
> 
> 1. Can u please add the relevant modifications to the Network CRD YAML file?

I listed `ClusterNetwork` and `NodeNetwork` that we need to modify or we need to create some new CRDs to fit the requirement.
I'm going to create some CRD examples for this enhancement.

> 2. Can you describe the changes involved in the upgrade first (maybe a solution will be added later)?

It will depend on implementation.
I will add it later if we have more discussion about details.

> 3. For network diagrams, prefer to change the `Not Possible` to `Not Support`

Updated.

Thanks a lot

**Comment by tjjh89017** [comment]
update example CRD design.

**Comment by tjjh89017** [comment]
close this
and track in https://github.com/harvester/harvester/pull/3066

**Pull request closed without merging**
