### PR TITLE
Fix code scanning alert - Log entries created from user input and incorrect conversion

### PR DESCRIPTION
**Pull request by futuretea**
**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

**Problem:**
- https://github.com/harvester/harvester/security/code-scanning/15
- https://github.com/harvester/harvester/security/code-scanning/22

**Solution:**
- use strconv.ParseInt instead of strconv.Atoi
- remove `\n` and '\r' from user input

**Related Issue:**
https://github.com/harvester/security/issues/20

**Test plan:**
- build the latest Harvester API server.
- replace with the custom image in any v1.1.2.x cluster.
- make sure it runs correctly and contains no extra error logs.

### CODE REVIEW

**Review by guangbochen — APPROVED** [review]
LGTM, thanks.

**Review by ibrokethecloud — APPROVED** [review]
LGTM.

**Review by chrisho — APPROVED** [review]
LGTM, thanks

**Comment by bk201** [comment]
@futuretea We need to backport this to the v1.1 branch as well.

**Comment by bk201** [comment]
@mergifyio backport v1.1

**Comment by futuretea** [comment]
> @futuretea We need to backport this to the v1.1 branch as well.

@bk201 Thanks

**Pull request merged**
