### PR TITLE
Bump Longhorn dependency to v1.4.1

### PR DESCRIPTION
**Pull request by guangbochen**
**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

**Problem:**
Need to bump Longhorn dependency to v1.4.1

**Solution:**
Bump Longhorn go mod and dependency chart to v1.4.1

**Related Issue:**
https://github.com/harvester/harvester/issues/3747

**Test plan:**
- build a new ISO image based on the current PR
- verify all pods are running correctly on the `longhorn-system` namespace
- create a VM and check that LH-related features are working as expected. (e.g., snapshot, backup and volumes)
image

### CODE REVIEW

**Review by futuretea — APPROVED** [review]
LGTM, vm creation, backup, snapshot work in v1.4.1

**Comment by FrankYang0529** [comment]
~Do we want to merge this first and then add the priority class? https://github.com/harvester/harvester/pull/3757~

Ignore this. We will update the priority-class in the upstream. Thanks.

**Review by FrankYang0529 — APPROVED** [review]
LGTM. Thanks.

Test VM creation, backup/snapshot, restore new, replace existing. All work fine.

**Review by Vicente-Cheng — APPROVED** [review]
Tested with volume creation, VM migration, snapshot, and backup. Looks fine.
LGTM!

**Review by bk201 — APPROVED** [review]

**Pull request merged**
