### PR TITLE
charts: bump harvester-node-disk-manager to v0.5.0

### PR DESCRIPTION
**Pull request by Vicente-Cheng**
**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

**Problem:**
Update Harvester-node-disk-manager to latest

**Solution:**
Update charts

**Related Issue:**
None

**Test plan:**
None

### CODE REVIEW

**Review by guangbochen — COMMENTED** [review]
can u also modify the version on the https://github.com/harvester/harvester/blob/v1.2/deploy/charts/harvester/values.yaml#L391, thanks.

**Comment by Vicente-Cheng** [comment]
> can u also modify the version on the https://github.com/harvester/harvester/blob/v1.2/deploy/charts/harvester/values.yaml#L391, thanks.

Updated!

**Review by guangbochen — APPROVED** [review]
LGTM, thanks.

**Review by chrisho — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
