### PR TITLE
feat: add support bundle node collection timeout

### PR DESCRIPTION
**Pull request by Yu-Jack**
**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

**Problem:**

Currently, there is no timeout for nodes when creating support bundle files, resulting in infinite waiting for node collection. That means we can't download support bundle file.

**Solution:**

- First, support node timeout in support-bundle-kit https://github.com/rancher/support-bundle-kit/pull/109.
- Second, provide custom setting of node timeout in harvester (this PR).

By this, we could still download support bundle file even node is timeout.

**Related Issue:**

https://github.com/harvester/harvester/issues/1646

**Test plan:**

Prepare:

1. Use new harvester with new support bundle kit image
2. Define `settings > support-bundle-node-collection-timeout` (unit is minute)
3. Create support bundle 
4. Check env fields of support bundle manager deployment

Two different cases:

- Case A: define large and enough minutes, it should get nodes folder successfully.
- Case B: define a small minute, like `"1"`. This one depends how long your environment takes. Just define a very small minute to make timeout happen. Although It won't get nodes folder, but It will get the support bundle file zip.

### CODE REVIEW

**Comment by Yu-Jack** [comment]
Cause https://github.com/longhorn/longhorn-manager/pull/2825 longhorn side uses `support-bundle-node-collection-timeout`, I think that one is more accurate, so I'll use it in harvester side, and for unite as well

**Review by bk201 — APPROVED** [review]
LGTM

**Review by ibrokethecloud — APPROVED** [review]
lgtm. thanks.

**Comment by Yu-Jack** [comment]
@Mergifyio backport v1.3

**Pull request merged**
