### PR TITLE
Addition of script for v1.0.1 ugprade which introduces monitoring fixes

### PR DESCRIPTION
**Pull request by ibrokethecloud**
**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

**Problem:**

This PR introduces the upgrade script for harvester upgrades from v1.0.1 to handle the patching of managed monitoring charts to include the diff for managed charts to ignore the modified Validating and Mutating webhook configurations.

**Solution:**

**Related Issue:**
https://github.com/harvester/harvester/issues/2152

This is related to harvester-installer PR: https://github.com/harvester/harvester-installer/pull/274

**Test plan:**

### CODE REVIEW

**Comment by bk201** [comment]
Thanks for the PR.
Because the upgrade support path is from 1.0.1 to 1.0.2, so we can assume some values are already there.
I'd say `patch_prometheus_resources` is the only migration we need for now.

**Comment by johnliu55tw** [comment]
With this fix, we could change the target upgraded state of `rancher-monitoring` from `modified` to `ready`:
https://github.com/harvester/harvester/blob/05b5da2dff3a9188a9d1defca30d905e326e7083/package/upgrade/upgrade_manifests.sh#L337-L338

@ibrokethecloud could you help replace `modified` with `ready`? Thanks!

**Comment by ibrokethecloud** [comment]
@johnliu55tw this is updated now.

**Review by johnliu55tw — APPROVED** [review]
LGTM

**Review by bk201 — APPROVED** [review]
LGTM.

**Pull request merged**
