### PR TITLE
bump golangci-lint and fix lint errors

### PR DESCRIPTION
**Pull request by guangbochen**
**Problem:**
`golang-ci` lint is not installed properly and was out-of-date.

**Solution:**
Bump `golangci-lint` and fix existing lint errors.

**Related Issue:**
N/A

**Test plan:**
- Pass the CI build.

### CODE REVIEW

**Comment by bk201** [comment]
cc @starbops There is some variable renaming in the upgrade path.

**Review by bk201 — APPROVED** [review]
LGTM

**Review by futuretea — APPROVED** [review]
LGTM

**Review by Vicente-Cheng — APPROVED** [review]
LGTM, thanks for fixing lint errors!

**Comment by guangbochen** [comment]
@mergify backport v1.1

**Pull request merged**
