### PR TITLE
Bump golang to v1.21

### PR DESCRIPTION
**Pull request by votdev**
**Problem:**
Go v1.20 is EOL on 06 Feb 2024.

**Solution:**
Bump golang to v1.21.

**Related Issue:**
https://github.com/harvester/harvester/issues/5310

### CODE REVIEW

**Review by FrankYang0529 — APPROVED** [review]
LGTM. I can provision a cluster with harvester-installer https://github.com/harvester/harvester-installer/pull/684.

**Review by Vicente-Cheng — APPROVED** [review]
lgtm, thanks for it!

**Review by bk201 — APPROVED** [review]
lgtm, thank you!

**Review by starbops — APPROVED** [review]
LGTM, thank you!

**Comment by FrankYang0529** [comment]
@Mergify backport v1.3

**Comment by FrankYang0529** [comment]
@mergify backport v1.2

**Pull request merged**
