### PR TITLE
Add Harvester v1.2.0 release

### PR DESCRIPTION
**Pull request by guangbochen**
**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

**Problem:**
Add Harvester v1.2.0 release

**Solution:**
Add Harvester v1.2.0 release

**Related Issue:**
https://github.com/harvester/harvester/issues/4294

**Test plan:**

### CODE REVIEW

**Review by futuretea — APPROVED** [review]
LGTM, thanks.
- [x] new cluster
- [x] upgrade from v1.1.2

**Review by chrisho — APPROVED** [review]
LGTM verified that as follows:
- Upgrade to v1.2.0 from v1.1.2.
- VM operations include backup, snapshots and restore.
- Provide a rke2 guest cluster(3 masters, 1workers) and backup one of the nodes and restore.
- Force shutdown of one node and restarting the VM took as expected.
- Enable cluster monitoring.

**Review by Vicente-Cheng — APPROVED** [review]
LGTM, tested with the upgrade path. All basic operations look fine.

**Review by starbops — APPROVED** [review]
Tested with two-node cluster upgrade. LGTM, thanks!

**Pull request merged**
