### PR TITLE
feat: add rancher application supported

### PR DESCRIPTION
**Pull request by thxCode**
https://github.com/rancher/harvester/issues/63

### CODE REVIEW

**Comment by guangbochen** [comment]
few issues need to address @thxCode : 
1. delete chart from catalog didn't clean-up all the resource(maybe is caused by rancher embed hem3)
2. allows user to enabled/disable each component like kubevirt, cdi and Minio
3. When Minio is disabled, s3 server endpoint and secret configuration should be required 
4. Minio persistence storage should be enabled by default and refer changes to https://github.com/guangbochen/helm3-charts/commit/9355bb67ecb024ecf1af715dace72189e615449d
5. set default namespace to `harvester-system` and app name to `harvester`, maybe refer to https://github.com/rancher/charts/blob/master/charts/longhorn/latest/questions.yml#L3 of how to do this.

**Review by guangbochen — COMMENTED** [review]
do you reckon we should also clean harvester CRD since its CR will be kept if we don't remove them?

**Comment by thxCode** [comment]
We can discuss this later, maybe use another PR to clean the CRs of the harvester.

**Review by guangbochen — APPROVED** [review]
LGTM, thanks

**Pull request merged**
