### PR TITLE
Bump Longhorn to v1.4.3

### PR DESCRIPTION
**Pull request by futuretea**
**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

Bump Longhorn to v1.4.3

**Related Issue:**
https://github.com/harvester/harvester/issues/3943

**Test plan:**

build a new ISO image based on the current PR

**case 1**
1. create a new cluster by the custom ISO image 
2. verify all pods are running correctly on the longhorn-system namespace
3. create a VM and check that LH-related features are working as expected. (e.g., snapshot, backup and volumes)

**case 2**
1. create a VM in Harvester v1.1.2 (a three nodes cluster)
2. take VM snapshot
3. upgrade the Harvester cluster by the custom iso image 
4. restore the VM snapshot to Create a new VM
5. the restore VM should be ready
6. verify all pods are running correctly on the longhorn-system namespace
7. create a VM and check that LH-related features are working as expected. (e.g., snapshot, backup and volumes)

### CODE REVIEW

**Review by guangbochen — APPROVED** [review]
LGTM, upgrade from v1.1.2 to this PR works, all LH pods are running correctly and was able to restore a new VM from the VM snapshot take before upgrade, thanks. 
image
image

**Review by bk201 — APPROVED** [review]
LGTM!

**Review by Vicente-Cheng — APPROVED** [review]
LGTM, verify with case 2. 
Upgrade successfully and restore/verify goods well.

**Comment by Vicente-Cheng** [comment]
@mergify backport v1.2

**Pull request merged**
