### PR TITLE
Fix harvester POD booting restarts error due to webhook is not ready

### PR DESCRIPTION
**Pull request by w13915984028**
**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

**Problem:**

Harvester POD does not wait harvester-webhook in proper sequence.

**Solution:**

Harvester POD waits for harvester-webhook properly.

**Related Issue:**
https://github.com/harvester/harvester/issues/4416

**Test plan:**

1. Install a new cluster, e.g. single-node cluser
2. Restart the cluster several times
3. `kubectl get pods -n harvester-system`, the `RESTARTS` of Harvester POD should be same as others.

### CODE REVIEW

**Comment by ibrokethecloud** [comment]
the current fix checks for template version and skips them if it exists, and will work during a restart.

I am wondering if it may be better to have a check in `Init` to ensure `harvester-webhook` is running before creating the objects?

**Comment by w13915984028** [comment]
> the current fix checks for template version and skips them if it exists, and will work during a restart.
> 
> I am wondering if it may be better to have a check in `Init` to ensure `harvester-webhook` is running before creating the objects?

@ibrokethecloud  below fix causes integration-test failed, let me try your suggestion today, thanks.
image

**Comment by w13915984028** [comment]
@ibrokethecloud 

In bootstrap stage, the harvester-webhook may have not registered itself. Wait in such case, seems not reasonable.

I am still checking,  why those objects are created from POD controller (source code) each starting, instead of from charts.

**Comment by w13915984028** [comment]
The even worse problem is:

Following `wait` is waiting for a static CRD object (created at the first time and then always there), it does not mean the `harvester-webhook` POD is up and ready. I encountered more restarts of Harvester POD as long as it starts up earlier than `harvester-webhook` POD.

```
// Wait waits for the admission webhook server to register ValidatingWebhookConfiguration and MutatingWebhookConfiguration resources.
func Wait(ctx context.Context, clientSet *kubernetes.Clientset) error {
	return wait.PollImmediate(PollingInterval, PollingTimeout, func() (bool, error) {
		logrus.Infof("Waiting for ValidatingWebhookConfiguration %s...", webhook.ValidatingWebhookName)
		_, err := clientSet.AdmissionregistrationV1().ValidatingWebhookConfigurations().Get(ctx, webhook.ValidatingWebhookName, metav1.GetOptions{})
```

The `wait` is almost useless.

```
time="2023-08-18T11:03:30Z" level=info msg="Waiting for ValidatingWebhookConfiguration harvester-validator..."
time="2023-08-18T11:03:30Z" level=info msg="Waiting for MutatingWebhookConfiguration harvester-mutator..."
time="2023-08-18T11:03:30Z" level=info msg="Admission webhooks are ready"

..
time="2023-08-18T11:03:40Z" level=fatal msg="failed to create harvester server: Internal error occurred: failed calling webhook \"validator.harvesterhci.io\": failed to call webhook: Post \"https://harvester-webhook.harvester-system.svc:443/v1/webhook/validation?timeout=10s\": context deadline exceeded"

```

The `harvester-webhook` start log:
```
harv41:~ # kk logs -n harvester-system harvester-webhook-74477784ff-jkcf7
time="2023-08-18T11:04:08Z" level=info msg="Starting webhook server"
time="2023-08-18T11:04:08Z" level=info msg="add validation handler for [nodes]. (Node)"
time="2023-08-18T11:04:08Z" level=info msg="add validation handler for [persistentvolumeclaims]. (PersistentVolumeClaim)"
time="2023-08-18T11:04:08Z" level=info msg="add validation handler for [keypairs].harvesterhci.io (KeyPair)"
```

**Comment by ibrokethecloud** [comment]
may be we should check if `harvester-webhook` svc has any valid endpoints?

**Comment by w13915984028** [comment]
With the current fix, the `harvester` POD will not simply panic due to `harvester-webhook` is not ready. It waits for the `harvester-webhook` pod.

The data init process is splited into two parts, and the second part is put behind the new `wait for webhook`.

```
harvester pods starts earlier, it waits harvester-webhook

harv41:~ # kk logs -n harvester-system harvester-5546fdc555-xj2lb
time="2023-08-23T07:22:37Z" level=info msg="Starting controller"
time="2023-08-23T07:22:38Z" level=info msg="Do not update the existing CRD KeyPair"
..

time="2023-08-23T07:22:39Z" level=info msg="Waiting for ValidatingWebhookConfiguration harvester-validator..."
time="2023-08-23T07:22:39Z" level=info msg="Waiting for MutatingWebhookConfiguration harvester-mutator..."
time="2023-08-23T07:22:39Z" level=info msg="Admission webhooks are ready"
time="2023-08-23T07:22:39Z" level=info msg="Waiting for harvester-webhook POD ..."
time="2023-08-23T07:22:44Z" level=info msg="Waiting for harvester-webhook POD ..."
time="2023-08-23T07:22:44Z" level=info msg="harvester-webhook POD harvester-webhook-74477784ff-jkcf7 is ready"
..
harv41:~ # kk logs -n harvester-system harvester-webhook-74477784ff-jkcf7
time="2023-08-23T07:22:43Z" level=info msg="Starting webhook server"
time="2023-08-23T07:22:43Z" level=info msg="add validation handler for [nodes]. (Node)"
```

A newly installed cluster, `harvester` pod did not restart due to panic.
```
newly installed cluster:
harv41:~ # kk get pods -n harvester-system
NAME                                                   READY   STATUS    RESTARTS      AGE
harvester-55dcc8c7f9-k8wfs                             1/1     Running   0             24m
..
harvester-node-disk-manager-wqm97                      1/1     Running   1 (24m ago)   24m
harvester-node-manager-hqzln                           1/1     Running   0             24m
harvester-webhook-79685df95-48m2m                      1/1     Running   0             24m
..
virt-handler-vrhml                                     1/1     Running   0             23m
virt-operator-5b4cfdf9dc-tqz7b                         1/1     Running   0             24m
harv41:~ # 
```

restarted several times, and `harvester` did not panic
```
harv41:~ # kk get pods -n harvester-system
NAME                                                   READY   STATUS     RESTARTS       AGE
harvester-55dcc8c7f9-k8wfs                             1/1     Running    2 (2m3s ago)   33m
..
harvester-webhook-79685df95-48m2m                      1/1     Running    2 (2m3s ago)   33m
..
```

`harvester` pod log, it waited until `harvester-webhook` POD is ready
```
time="2023-08-23T08:30:01Z" level=info msg="Do not update the existing CRD NodeConfig"
time="2023-08-23T08:30:01Z" level=info msg="Waiting for ValidatingWebhookConfiguration harvester-validator..."
time="2023-08-23T08:30:01Z" level=info msg="Waiting for MutatingWebhookConfiguration harvester-mutator..."
time="2023-08-23T08:30:01Z" level=info msg="Admission webhooks are ready"
time="2023-08-23T08:30:01Z" level=info msg="Waiting for harvester-webhook POD ..."
time="2023-08-23T08:30:06Z" level=info msg="Waiting for harvester-webhook POD ..."
time="2023-08-23T08:30:11Z" level=info msg="Waiting for harvester-webhook POD ..."
time="2023-08-23T08:30:11Z" level=info msg="harvester-webhook POD harvester-webhook-79685df95-48m2m is ready"
```

**Comment by w13915984028** [comment]
@guangbochen @bk201 @ibrokethecloud 

The fix can be reviewed and verified now. thanks.

**Comment by w13915984028** [comment]
**Note: the current fix can still not 100% solve all potential panics, but eliminates most.**

Both `ContainersReady` and `Ready` of `harvester-webhook` are at "2023-08-23T10:37:08Z", the error is ` 2023-08-23T10:37:09Z ... proxy error from 127.0.0.1:9345 ... 503 Service Unavailable`.

**Unless the `harvester-webhook` is having a https endpoint for detecting the service readiness. or some other alternatives.**

harvester:
```
time="2023-08-23T10:37:03Z" level=info msg="Do not update the existing CRD NodeConfig"
time="2023-08-23T10:37:03Z" level=info msg="Waiting for ValidatingWebhookConfiguration harvester-validator..."
time="2023-08-23T10:37:03Z" level=info msg="Waiting for MutatingWebhookConfiguration harvester-mutator..."
time="2023-08-23T10:37:03Z" level=info msg="Admission webhooks are ready"
time="2023-08-23T10:37:03Z" level=info msg="Waiting for harvester-webhook POD ..."
time="2023-08-23T10:37:08Z" level=info msg="Waiting for harvester-webhook POD ..."
time="2023-08-23T10:37:08Z" level=info msg="harvester-webhook POD harvester-webhook-79685df95-48m2m is ready"
I0823 10:37:09.094098       7 leaderelection.go:248] attempting to acquire leader lease kube-system/harvester-controllers...
I0823 10:37:09.181410       7 leaderelection.go:258] successfully acquired lease kube-system/harvester-controllers
time="2023-08-23T10:37:09Z" level=fatal msg="failed to create harvester server: Internal error occurred: failed calling webhook \"validator.harvesterhci.io\": failed to call webhook: Post \"https://harvester-webhook.harvester-system.svc:443/v1/webhook/validation?timeout=10s\": proxy error from 127.0.0.1:9345 while dialing 10.52.0.244:9443, code 503: 503 Service Unavailable"
harv41:~ # 
```
harvester-webhook
```
harv41:~ # kk logs -n harvester-system harvester-webhook-79685df95-48m2m
time="2023-08-23T10:37:09Z" level=info msg="Starting webhook server"
time="2023-08-23T10:37:09Z" level=info msg="add validation handler for [nodes]. (Node)"
time="2023-08-23T10:37:09Z" level=info msg="add validation handler for [persistentvolumeclaims]. (PersistentVolumeClaim)"
...
```

harvester-webhook pod:
```
harv41:~ # kk get pod -n harvester-system harvester-webhook-79685df95-48m2m -oyaml
...
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-08-23T07:56:11Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-08-23T10:37:08Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-08-23T10:37:08Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-08-23T07:56:11Z"
    status: "True"
    type: PodScheduled
```

**Pull request closed without merging**
