### PR TITLE
Migrate Drone to GitHub Actions

### PR DESCRIPTION
**Pull request by FrankYang0529**
**Related Issue:**
https://github.com/harvester/harvester/issues/5327

### CODE REVIEW

**Comment by FrankYang0529** [comment]
Sample build: https://github.com/FrankYang0529/harvester/actions/runs/8811780703

**Review by bk201 — APPROVED** [review]
LGTM

**Review by Yu-Jack — COMMENTED** [review]
haven't finish reviewing, but a quick question, do you think we need to split the flow into different workflows for readability?

**Comment by FrankYang0529** [comment]
> haven't finish reviewing, but a quick question, do you think we need to split the flow into different workflows for readability?

I would prefer to keep current format. We can do improvement after all pipeline work fine. Thank you.

**Review by Yu-Jack — APPROVED** [review]
LGTM, thanks!

**Comment by FrankYang0529** [comment]
@mergify backport v1.2 v1.3

**Pull request merged**
