### PR TITLE
Addition of helm chart for vm-import-controller

### PR DESCRIPTION
**Pull request by ibrokethecloud**
**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

**Problem:**

Introduction of helm chart for vm-import-controller
https://github.com/harvester/vm-import-controller

**Solution:**

**Related Issue:** https://github.com/harvester/harvester/issues/2274

**Test plan:**

### CODE REVIEW

**Review by guangbochen — COMMENTED** [review]
We may consider to add the chart to https://github.com/harvester/charts if:
1. this chart can be installed/upgraded independently without directly bonded to the Harvester installation.
2. to leverage the CI chart validations from the harvester/charts repo.

**Comment by ibrokethecloud** [comment]
thanks for the feedback @guangbochen. The chart is now available at: https://github.com/harvester/charts/pull/97

Once published I will update this PR to reflect dependency from the new chart.

**Review by guangbochen — APPROVED** [review]
LGTM, thanks.

**Review by bk201 — APPROVED** [review]
lgtm

**Pull request merged**
