### PR TITLE
Add Harvester v1.0.0-rc2 release

### PR DESCRIPTION
**Pull request by guangbochen**
Add Harvester v1.0.0-rc2 release

- [x] tag `harvester`, `harvester-webhook` and `harvester-upgrade` to `v1.0.0-rc2`
- [x] tag harvester-installer to [v0.2.8](https://github.com/harvester/harvester-installer/releases) 
- [x] tag harvester-dashboard to [v1.0.0-rc2](https://github.com/harvester/dashboard/releases)
- [x] tag harvester-network-controller to [v0.2.6](https://github.com/harvester/network-controller-harvester/releases)
- [x] tag harvester-node-disk-managet to [v0.4.0](https://github.com/harvester/node-disk-manager/releases)
- [x] Longhorn already bumped to v1.2.3-rc2, Kubevirt has no version bump required
- [x] tag harvester-load-balancer to [v0.1.1](https://github.com/harvester/load-balancer-harvester/releases)

v1.0.0-rc2 commit change https://github.com/harvester/harvester/pull/1688/commits/64b5a23b118a2627f07bc94a2c24581d3274d949

### CODE REVIEW

**Comment by weihanglo** [comment]
Do we need these manual checks as well? https://github.com/harvester/harvester/pull/1605#pullrequestreview-820127460

**Comment by guangbochen** [comment]
> Do we need these manual checks as well? [#1605 (review)](https://github.com/harvester/harvester/pull/1605#pullrequestreview-820127460)

I was planning to use the v1.0 ISO image to test it after it gets merged but before we cut the RC2 release.

**Review by weihanglo — APPROVED** [review]
I believe it's good to merge and validate the image afterwards.

**Review by bk201 — APPROVED** [review]
LGTM

**Review by gitlawr — APPROVED** [review]
LGTM

**Pull request merged**
