### PR TITLE
Bump longhorn to v1.6.2 rc2

### PR DESCRIPTION
**Pull request by FrankYang0529**
**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

**Problem:**

**Solution:**

**Related Issue:**

**Test plan:**

### CODE REVIEW

**Review by bk201 — APPROVED** [review]
LGTM

**Review by bk201 — APPROVED** [review]
LGTM!

**Comment by bk201** [comment]
@mergifyio backport v1.3

**Review by Vicente-Cheng — APPROVED** [review]
LGTM, tested with a fresh installation

Basic volume operations look well.

**Pull request merged**
