### PR TITLE
Format memory Quantity to Gi in version_syncer

### PR DESCRIPTION
**Pull request by futuretea**
**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

Format memory Quantity to Gi in version_syncer

**Related Issue:**
https://github.com/harvester/security/issues/17

**Test plan:**

```bash
make test
```

### CODE REVIEW

**Review by guangbochen — APPROVED** [review]
LGTM, thanks.

**Review by FrankYang0529 — APPROVED** [review]
LGTM. Thanks.

**Review by bk201 — APPROVED** [review]
LGTM, thanks!

**Comment by bk201** [comment]
@Mergifyio backport v1.1

**Pull request merged**
