### PR TITLE
upgrade pcidevices controller addon manifest

### PR DESCRIPTION
**Pull request by ibrokethecloud**
**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

**Problem:**

Upgrade pcidevices addon to new rc as part of the upgrade

**Solution:**

**Related Issue:**
Related to pcidevices controller changes.

One of the related issues is: https://github.com/harvester/harvester/issues/3146

**Test plan:**

### CODE REVIEW

**Comment by guangbochen** [comment]
Can we please help to fix the CI error? and it was introduced in a different PR https://github.com/harvester/harvester/pull/3405 which is not rebased properly first, thanks.

**Review by guangbochen — APPROVED** [review]
LGTM, thanks.

**Review by bk201 — APPROVED** [review]
LGTM

**Comment by ibrokethecloud** [comment]
@mergify backport v1.1

**Pull request merged**
