### PR TITLE
bump: support-bundle-kit to v0.0.40

### PR DESCRIPTION
**Pull request by Yu-Jack**
**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

**Solution:**
Just a bumping.

**Related Issue:**
https://github.com/harvester/harvester/issues/4993

**Test plan:**
Be able to download support bundle files.

### CODE REVIEW

**Comment by Vicente-Cheng** [comment]
Hi @Yu-Jack, the target branch should be v1.4.

Seems the feature is marked for v1.4.0

**Review by FrankYang0529 — APPROVED** [review]
LGTM. Thank you.

**Comment by Yu-Jack** [comment]
@Vicente-Cheng Thanks. Let me close this.

**Comment by Yu-Jack** [comment]
@Vicente-Cheng @FrankYang0529 I changed to v1.4, thanks!

**Review by Vicente-Cheng — APPROVED** [review]
LGTM! Let's wait for the CI pass.

**Comment by tserong** [comment]
CI passed, I'll merge this now

**Pull request merged**
