### PR TITLE
Bump: Longhorn to v1.7.2-rc2

### PR DESCRIPTION
**Pull request by Yu-Jack**
Bump LH to v1.7.2-rc2.

### CODE REVIEW

**Review by WebberHuang1118 — APPROVED** [review]
LGTM, thanks for the PR.

Verified with VMImage creation
- Uploading
- Downloading
- Exporting

Verified with backup restore operations
- Creating VMbackup from a running VM
- Creating VMbackup from a stopped VM
- Restoring VMbackup to a new VM
- Restoring VMbackup to a new VM in different NS

**Comment by Yu-Jack** [comment]
LH team will release rc2 tomorrow, I think we can wait for one more day.

**Comment by Yu-Jack** [comment]
Verified with VM image creation

- Uploading
- Downloading
- Exporting

Verified with snapshot restore operations

- Creating VM snapshot from a running VM
- Creating VM snapshot from a stopped VM
- Restoring VM snapshot to a new VM

cc @bk201 @WebberHuang1118

**Review by bk201 — APPROVED** [review]
LGTM, thanks!

**Review by WebberHuang1118 — APPROVED** [review]
> Verified with VM image creation
> 
> * Uploading
> * Downloading
> * Exporting
> 
> Verified with snapshot restore operations
> 
> * Creating VM snapshot from a running VM
> * Creating VM snapshot from a stopped VM
> * Restoring VM snapshot to a new VM
> 
> cc @bk201 @WebberHuang1118

LGTM, thanks for the PR.

Aside from the above, I also verified with backup restore operations
- Creating VMbackup from a running VM
- Creating VMbackup from a stopped VM
- Restoring VMbackup to a new VM
- Restoring VMbackup to a new VM in a different NS

**Pull request merged**
