### PR TITLE
Dependency chart: bump Whereabouts to v0.6.2

### PR DESCRIPTION
**Pull request by WebberHuang1118**
**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

**Problem:**

Bump Whereabout to v0.6.2

**Solution:**

Whereabout to v0.6.2

**Related Issue:**
https://github.com/harvester/security/issues/31

**Test plan:**

**Deploy to running Harvester**
- Build Harvester cluster from Master 
- Enter pod `harvester-cluster-repo-xxxx`
  - $ zypper install -y tar gzip vim awk
  - $ curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
  - $ chmod 700 get_helm.sh
  - $ ./get_helm.sh
  - $ cd /srv/www/htdocs/charts/
  - $ tar zxvf harvester-0.0.0-master-xxxx.tgz
  - $ cd harvester
  - Edit `dependency_charts/whereabouts/templates/cluster_role.yaml` as https://github.com/harvester/harvester/commit/6f4647b2a14201a0b9602f61018de8c95c8279ae#diff-68d6083d3b14b99745ebec834362446dfce30eaae514fc2d8a0ef62356164194
  - Edit `dependency_charts/whereabouts/templates/daemonset.yaml l` as https://github.com/harvester/harvester/commit/6f4647b2a14201a0b9602f61018de8c95c8279ae#diff-f5b2c56ecf7b81e2c63f48afe93adffbf2c0a81570b673cb3365738e0bdee6f6
  - Edit values.yaml as https://github.com/harvester/harvester/commit/6f4647b2a14201a0b9602f61018de8c95c8279ae#diff-1e557ee14cc96a67bfde9c7a2f9b5099c4453a72d8cbe98dd3babfce02a1557b
  - $ rm -rf charts/whereabouts/
  - $ helm dependency update
  - $ cd ../ 
  - $ rm harvester-0.0.0-master-xxxx.tgz
  - $ tar zcvf harvester-0.0.0-xxxx.tgz harvester
  - Deleting pod fleet-agent-xxxx
  - Checking if daemoset harvester-whereabouts successfuly deploying image `ghcr.io/k8snetworkplumbingwg/whereabouts:v0.6.2-amd64`
  - Checking image upload from local
  - Enable Storage Network
  - Checking if Longhorn `backing-image-manager-xxxx` pods, `instance-manager-e-xxxx` pods, `instance-manager-r-xxxx` pods and `backing-image-ds-xxxx` pods (only appearing during uploading) have interface `lhnet1` and its ip in assigned range
  - Creating VM from uploaded image

**Building New Harvester with this PR**
- Build ISO from this branch, and creating Harvester cluster with the ISO
- After Harvester brought up, Check if daemoset harvester-whereabouts successfuly deploying image `ghcr.io/k8snetworkplumbingwg/whereabouts:v0.6.2-amd64`
- Checking if daemoset harvester-whereabouts successfuly deploying image `ghcr.io/k8snetworkplumbingwg/whereabouts:v0.6.2-amd64`
- Checking image upload from local
- Enable Storage Network
- Checking if Longhorn `backing-image-manager-xxxx` pods, `instance-manager-e-xxxx` pods, `instance-manager-r-xxxx` pods and `backing-image-ds-xxxx` pods (only appearing during uploading) have interface `lhnet1` and its ip in assigned range
- Creating VM from uploaded image

### CODE REVIEW

**Review by guangbochen — COMMENTED** [review]
please skip adding other generated charts except for the whereabouts one, thanks.

**Comment by WebberHuang1118** [comment]
> please skip adding other generated charts except for the whereabouts one, thanks.

Updated per suggestion, thanks.

**Review by bk201 — APPROVED** [review]
LGTM.
Tested
- new cluster and enable storage network.
- 1.1.2 cluster with storage network + upgrade.

Charts are bumped and images new updated.

**Review by guangbochen — APPROVED** [review]
LGTM, thanks.

**Comment by guangbochen** [comment]
@mergify backport v1.2

**Comment by bk201** [comment]
@mergifyio backport v1.1

**Pull request merged**
