### PR TITLE
[v1.1 backport] Bump SLE BCI image to 15.4

### PR DESCRIPTION
**Pull request by masteryyh**
**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

**Problem:**
Harvester components base image needs to update.

**Solution:**

Upgrade base image from SLE BCI 15.3 to 15.4

**Related Issue:**
[#3149](https://github.com/harvester/harvester/issues/3149)

### CODE REVIEW

**Review by bk201 — APPROVED** [review]
LGTM!

**Review by guangbochen — COMMENTED** [review]
Why is this not identical with https://github.com/harvester/harvester/commit/8ffb7da5773ee766c92f02fe5a3a674ca51f112a since this is a backport PR, can we cherry-pick the one from master instead? thanks.

**Review by guangbochen — APPROVED** [review]
LGTM, thanks.

**Review by Vicente-Cheng — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
