### PR TITLE
fix 1034, in rare cases, CI reports "failed to post disableMaintenanceMode action"

### PR DESCRIPTION
**Pull request by w13915984028**
**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

**Problem:**

Harvester integration reports `"failed to post disableMaintenanceMode action"`

It is occasional failure:
`failed to post disableMaintenanceMode action, response with 500, Operation cannot be fulfilled on nodes "harvester-control-plane": the object has been modified; please apply your changes to the latest version and try again`

**Solution:**

When try “`disableMaintenanceMode`”, the “`toUpdate`” is taken from “nodeCache.Get(name)”, when finally nodeClient.Update(node), the “toUpdate” has been changed by others (not always), thus the API Server complains “the object has been modified; please apply your changes to the latest version and try again”

Check conflict error, when it happens, get node again via nodeClient, then try updating

**Related Issue:**
#1034 

**Test plan:**

keep watching drone CI, check if same failure happens again

### CODE REVIEW

**Comment by bk201** [comment]
We have similar situations in two places. Do you think it's better to add some delay and retry more times?
- https://github.com/harvester/harvester/blob/c2c025a51b78788d4d6dcc8522df8077e6651de5/pkg/api/image/formatter.go#L150-L175
- https://github.com/harvester/harvester/blob/c2c025a51b78788d4d6dcc8522df8077e6651de5/pkg/controller/master/upgrade/node_controller.go#L89-L93

**Comment by w13915984028** [comment]
> We have similar situations in two places. Do you think it's better to add some delay and retry more times?
> 
> * https://github.com/harvester/harvester/blob/c2c025a51b78788d4d6dcc8522df8077e6651de5/pkg/api/image/formatter.go#L150-L175
> * https://github.com/harvester/harvester/blob/c2c025a51b78788d4d6dcc8522df8077e6651de5/pkg/controller/master/upgrade/node_controller.go#L89-L93

@bk201  will check. in CI test, it´s better to delay a while to let others finish their operations.

**Comment by w13915984028** [comment]
The log snippet from drone build of : `commit f733fe46468`
https://drone-pr.rancher.io/harvester/harvester/1702/1/2

the retry of "disable maintenance mode" will try best to update node in case conflicts caused by other components updating node in parallel

"
...
------------------------------
verify host APIs operate via steve API 
  verify host maintenance mode
  /go/src/github.com/harvester/harvester/tests/integration/api/host_apis_test.go:42
STEP: enable maintenance mode of the host
STEP: then the node is unschedulable and maintain-status is set

time="2022-01-17T15:43:55Z" level=error msg="error syncing 'ssl-certificates': handler harvester-setting-controller: helmchartconfigs.helm.cattle.io \"rke2-ingress-nginx\" not found, requeuing"

STEP: disable maintenance mode of the host
STEP: then the node is schedulable and maintain-status is removed
"

**Comment by w13915984028** [comment]
@bk201 Please take a look of the new update, thanks.

**Review by FrankYang0529 — APPROVED** [review]
LGTM

**Review by bk201 — APPROVED** [review]
LGTM, thanks for addressing the flaky CI issue.

**Review by guangbochen — APPROVED** [review]

**Pull request merged**
