### PR TITLE
chore: bump kube-vip to v0.8.0

### PR DESCRIPTION
**Pull request by starbops**
**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

**Problem:**

**Solution:**

Bump the image tag to v0.8.0 and the chart to 0.5.0

**Related Issue:**

harvester/security#49

**Test plan:**

Several things to check:

- For newly installed/upgraded clusters
  - Check if control-plane VIP works
  - Check if VM load balancer works

### CODE REVIEW

**Comment by starbops** [comment]
Need to be back-ported to v1.2 & v1.3 branches.

**Review by bk201 — APPROVED** [review]
lgtm! VIP works.

**Review by mingshuoqiu — APPROVED** [review]
LGTM. VIP and LB works w/o problem

**Comment by starbops** [comment]
@mergify backport v1.2

**Comment by starbops** [comment]
@mergify backport v1.3

**Pull request merged**
