### PR TITLE
upgrade: misc enhancement for witness node

### PR DESCRIPTION
**Pull request by Vicente-Cheng**
**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

**Problem:**
Upgrade stuck with witness node scenario

**Solution:**
improve the upgrade related jobs

**Related Issue:**
https://github.com/harvester/harvester/issues/5192

**Test plan:**
1. Create a cluster with one witness node
2. Check the upgrade result

### CODE REVIEW

**Comment by bk201** [comment]
I can see preparing job on witness role work now, but seems at the later stage, the `skip-restart-rancher-system-agent` can't finish: https://github.com/harvester/harvester/blob/db569a30aff50493ea7a178448f93adc09b38179/package/upgrade/upgrade_manifests.sh#L1131
Can you also help fix the plan? Thanks!

**Comment by bk201** [comment]
The issue only happens in air-gap env, because registry.suse.com/bci/bci-base:15.4 doesn't exist anymore: https://github.com/harvester/harvester/blob/db569a30aff50493ea7a178448f93adc09b38179/package/upgrade/upgrade_manifests.sh#L1155
We can bump to 15.5 together

**Comment by Vicente-Cheng** [comment]
> The issue only happens in air-gap env, because registry.suse.com/bci/bci-base:15.4 doesn't exist anymore:
> 
> https://github.com/harvester/harvester/blob/db569a30aff50493ea7a178448f93adc09b38179/package/upgrade/upgrade_manifests.sh#L1155
> 
> 
> We can bump to 15.5 together

Nice catch!
Updated to bci-base:15.5

**Review by bk201 — APPROVED** [review]
lgtm!

**Review by starbops — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
