### PR TITLE
HEP: System robustness enhancement [CI SKIP]

### PR DESCRIPTION
**Pull request by w13915984028**
**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

    HEP: System robustness enhancement
    
    Signed-off-by: Jian Wang <w13915984028@gmail.com>

**Problem:**

How to gracefully shutdown an running Harvester cluster? no clear answer yet.

**Solution:**

Add to a new feature to accomplish this.

**Related Issue:**
https://github.com/harvester/harvester/issues/3261

One previous DOC PR: [docs: add cluster shutdown and restart](https://github.com/harvester/docs/pull/268)

**Test plan:**

### CODE REVIEW

**Comment by w13915984028** [comment]
BTW: all review comments are welcome, thanks.

**Comment by vtrenton** [comment]
Brainstorming:
1. Shut down VMs using kube-virt graceful shutdown process: https://github.com/kubevirt/kubevirt/blob/main/docs/graceful-shutdown.md
2. signal k8s to drain/cordon harvester node.
3. assure all workloads like longhorn have been removed from the node
4. shutdown node

oversimplifying a bit - but might be a good start.

**Comment by markhillgit** [comment]
reopening, this is still meant to be active

**Comment by markhillgit** [comment]
ping, keeping this PR active

**Pull request closed without merging**
