### PR TITLE
Bump chart version

### PR DESCRIPTION
**Pull request by brandboat**
related to https://github.com/harvester/harvester/issues/6158,

bump harvester-network-controller to 0.5.1
bump harvester-node-disk-manager to 0.7.2
bump harvester-load-balancer to 0.4.0
bump harvester-node-manager to 0.3.0

### CODE REVIEW

**Comment by FrankYang0529** [comment]
Hi @ibrokethecloud, it looks like harvester-network-controller v0.5.0 uses empty tag for `rancher/harvester-network-controller`. Do we intend to do that? Thanks.

https://github.com/harvester/charts/blob/751ce7b812900cc6b816fde27a0742c834011e21/charts/harvester-network-controller/values.yaml#L4-L8

**Comment by FrankYang0529** [comment]
> Hi @ibrokethecloud, it looks like harvester-network-controller v0.5.0 uses empty tag for `rancher/harvester-network-controller`. Do we intend to do that? Thanks.
> 
> https://github.com/harvester/charts/blob/751ce7b812900cc6b816fde27a0742c834011e21/charts/harvester-network-controller/values.yaml#L4-L8

Sorry, it looks like we use `appVersions` to override it. However, not sure why my cluster from this branch uses `master-head` for images. 🤔

**Comment by bk201** [comment]
@FrankYang0529 In t he master branch, we always use master-head images. that's intentional. (override in https://github.com/harvester/harvester/blob/c5d790422fbf02fecbd7401113183cdf95bc8cfc/deploy/charts/harvester/values.yaml#L354)

**Review by bk201 — APPROVED** [review]
Thanks!

**Comment by FrankYang0529** [comment]
Got it. So `values.yaml` in harvester override all chart image tag.

**Review by FrankYang0529 — APPROVED** [review]

**Comment by brandboat** [comment]
convert to draft as we need to wait until NDM 0.7.2 release, more info, see https://github.com/harvester/charts/pull/268
https://github.com/harvester/charts/pull/272

**Review by bk201 — APPROVED** [review]
LGTM!

**Pull request merged**
