### PR TITLE
fix(upgrade): replace instance manager count check with state check

### PR DESCRIPTION
**Pull request by FrankYang0529**
**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

**Problem:**
Currently, the engine process can't be live migrated to a new longhorn instance manager, so there may be two IM at the same time. We have to improve our upgrade check for instance manager.

Ref: [Troubleshooting: Some old instance manager pods are still running after upgrade](https://longhorn.io/kb/troubleshooting-some-old-instance-manager-pods-are-still-running-after-upgrade/)

**Solution:**
Check whether new instance manager is running.

**Related Issue:**
https://github.com/harvester/harvester/issues/4879

**Test plan:**
1. Create a v1.2.1 Harvester cluster.
2. Create a VM.
3. Upgrade to v1.2-head with LH v1.5.3 (https://github.com/harvester/harvester/pull/5057).
4. Upgrade to this branch again. Instance manager check should pass without any error.

### CODE REVIEW

**Review by markhillgit — APPROVED** [review]
lgtm thanks

**Review by ibrokethecloud — APPROVED** [review]
lgtm. thanks.

**Review by Vicente-Cheng — APPROVED** [review]
LGTM, tested with https://github.com/harvester/harvester/pull/5087
upgrade path from v1.2.1 -> v1.2-head (with Longhorn v1.5.3) -> master-head (with this PR)

verified the VM can be migrated (w/o vlan due to https://github.com/harvester/harvester/issues/5076)
And all basic operations work well.

Also tested the snapshot/backup/restore work well.

**Comment by FrankYang0529** [comment]
@mergify backport v1.2

**Pull request merged**
