### PR TITLE
Add Harvester v1.0.3-rc1 head

### PR DESCRIPTION
**Pull request by guangbochen**
**Description:**
Add Harvester v1.0.3-rc1 head

Dependencies:
- [x] bump Harvester-installer to v1.0.3-rc1
- [x] bump NDM to [v0.4.4](https://github.com/harvester/node-disk-manager/releases/tag/v0.4.4)
- [x] change kube-vip helm repo url to https://kube-vip.github.io/helm-charts due to https://github.com/kube-vip/helm-charts/issues/14

### CODE REVIEW

**Review by bk201 — APPROVED** [review]
lgtm

**Review by FrankYang0529 — APPROVED** [review]
LGTM. It works fine on my computer.

**Comment by guangbochen** [comment]
Added NDM version bump commit https://github.com/harvester/harvester/pull/2548/commits/63afe757c20a09c8b1541621b9f1c281f63ed431, please help to verify it again, and sorry for the late changes.

**Review by bk201 — APPROVED** [review]
Verify NDM bumped and can add disks.

**Review by FrankYang0529 — APPROVED** [review]
LGTM. Following test cases are passed.

* Create a 3-node cluster. All nodes can become management nodes.
* VM Backup/Restore.
* Provision RKE2 on Harvester.

**Pull request merged**
