### PR TITLE
feat: update wharfie to v0.6.3

### PR DESCRIPTION
**Pull request by FrankYang0529**
**Related Issue:**
https://github.com/harvester/security/issues/36#top

### CODE REVIEW

**Review by Vicente-Cheng — APPROVED** [review]
LGTM, thanks!

**Review by bk201 — APPROVED** [review]
lgtm

**Comment by FrankYang0529** [comment]
https://github.com/Mergifyio backport v1.2

**Comment by FrankYang0529** [comment]
https://github.com/Mergifyio backport v1.1

**Pull request merged**
