### PR TITLE
feat: bump longhorn to v1.5.3

### PR DESCRIPTION
**Pull request by FrankYang0529**
**Related Issue:**
https://github.com/harvester/harvester/issues/4606

**Test plan:**
1. Test VM can work.
2. Test Backup/Snapshot can work.

### CODE REVIEW

**Comment by ibrokethecloud** [comment]
we should also package a few more dependencies in the base OS image to allow longhorn v2 engine support

**Comment by ibrokethecloud** [comment]
here are the sample changes needed in the installer for the same: https://github.com/ibrokethecloud/harvester-installer/blob/longhorn-v1.5.1/package/harvester-os/Dockerfile#L11-L14

**Comment by bk201** [comment]
> here are the sample changes needed in the installer for the same: https://github.com/ibrokethecloud/harvester-installer/blob/longhorn-v1.5.1/package/harvester-os/Dockerfile#L11-L14

We can do this together with https://github.com/harvester/harvester/issues/4745, @jeff-radick-suse  I added `uuid-develp` to the ticket.

**Comment by bk201** [comment]
We can remove unchanged dep chart tarballs in the PR. The rest looks good to me.

**Comment by WebberHuang1118** [comment]
The [LH related packages](https://github.com/FrankYang0529/harvester/blob/048fb84ff956615088255a92263277acc01793ad/go.mod#L79-L80) may also align to LH v1.5.3. The backupstore version is [v0.0.0-20231025000449-5316e8b5320d](https://github.com/longhorn/longhorn-manager/blob/88c792f7df38383634c2c8401f96d999385458c1/go.mod#L48) in LH v1.5.3.

**Comment by FrankYang0529** [comment]
> We can remove unchanged dep chart tarballs in the PR. The rest looks good to me.

> The [LH related packages](https://github.com/FrankYang0529/harvester/blob/048fb84ff956615088255a92263277acc01793ad/go.mod#L79-L80) may also align to LH v1.5.3. The backupstore version is [v0.0.0-20231025000449-5316e8b5320d](https://github.com/longhorn/longhorn-manager/blob/88c792f7df38383634c2c8401f96d999385458c1/go.mod#L48) in LH v1.5.3.

Updated both. Thank you.

**Review by bk201 — APPROVED** [review]
LGTM!

**Review by WebberHuang1118 — APPROVED** [review]
Testing with VM creation, VM Backup, and VM Restore, basic operations work as expected.

LGTM, thanks.

**Review by Vicente-Cheng — APPROVED** [review]
Tested with https://github.com/harvester/harvester/pull/4760
All basic operations work well, and the downstream cluster works well.
LGTM, thanks!

**Pull request merged**
