### PR TITLE
bump golang to v1.20.10

### PR DESCRIPTION
**Pull request by FrankYang0529**
**Problem:**
We used go 1.18, which is EOL in 2023/02.

**Solution:**
Bump golang to v1.20.10.

**Related Issue:**
https://github.com/harvester/security/issues/38

### CODE REVIEW

**Comment by Vicente-Cheng** [comment]
Hi @FrankYang0529,
Please rebase to fix CI error. Thanks!

**Review by bk201 — APPROVED** [review]
LGTM, thanks!

**Review by ibrokethecloud — APPROVED** [review]
LGTM. thanks.

**Comment by FrankYang0529** [comment]
@Mergifyio backport v1.1 v1.2

**Pull request merged**
