### PR TITLE
chart: Bump longhorn to v1.3.2

### PR DESCRIPTION
**Pull request by Vicente-Cheng**
related issues: 
https://github.com/harvester/harvester/issues/2911
https://github.com/harvester/harvester/issues/2920

### CODE REVIEW

**Comment by guangbochen** [comment]
May need to update it again if https://github.com/harvester/harvester/pull/2940 is merged first. 😃

**Comment by Vicente-Cheng** [comment]
> May need to update it again if #2940 is merged first. 😃

OK, I would check it.

**Review by guangbochen — APPROVED** [review]
LGTM, thanks.

**Review by bk201 — APPROVED** [review]
LGTM

**Pull request merged**
