### PR TITLE
Connect Virtual Image and Backing Image by vmi's UID

### PR DESCRIPTION
**Pull request by WebberHuang1118**
**Problem:**
Creating two virtual images with the same `<namespace>-<name>` combination will lead to one virtual image stuck in creation (progress stays 0%)

**Solution:**
Naming backing image from virtual image's uid

**Related issue:**
#5123

**Test plan:**

Case1: Two virtual image with the same `<namespace>-<name>` combination
- Creating namespace `harvester`
- Applying the following two manifests at the same time
  ```
  apiVersion: harvesterhci.io/v1beta1
  kind: VirtualMachineImage
  metadata:
    name: ubuntu
    namespace: harvester-public
  spec:
    displayName: ubuntu
    retry: 3
    sourceType: download
    storageClassParameters:
      migratable: "true"
      numberOfReplicas: "1"
      staleReplicaTimeout: "30"
    url: <image download url>
  ```
  ```
  apiVersion: harvesterhci.io/v1beta1
  kind: VirtualMachineImage
  metadata:
    name: public-ubuntu
    namespace: harvester
  spec:
    displayName: public-ubuntu
    retry: 3
    sourceType: download
    storageClassParameters:
      migratable: "true"
      numberOfReplicas: "1"
      staleReplicaTimeout: "30"
    url: <image download url>
  ```
- The two images should be created successfully and could be used to provide VM

Case 2: Creating an image with a name length longer than 40 characters
- Applying the following manifest
  ```
  apiVersion: harvesterhci.io/v1beta1
  kind: VirtualMachineImage
  metadata:
    name: ubuntu-jammy-123456789012345678901234567890
    namespace: default
  spec:
    checksum: ""
    displayName: img-longname
    pvcName: ""
    pvcNamespace: ""
    retry: 3
    sourceType: download
    storageClassParameters:
      migratable: "true"
      numberOfReplicas: "1"
      staleReplicaTimeout: "30"
    url: <image download url>
  ```
- The image should be created successfully and could be used to provide a VM

### CODE REVIEW

**Review by FrankYang0529 — APPROVED** [review]
LGTM. All functions work as expected. Thanks.

**Review by FrankYang0529 — APPROVED** [review]
LGTM. All test cases can pass.

**Review by bk201 — APPROVED** [review]
LGTM, thanks!

**Comment by WebberHuang1118** [comment]
@mergify backport v1.4

**Comment by WebberHuang1118** [comment]
@mergify backport v1.3

**Pull request merged**
