### PR TITLE
Patch kubevirt image and bump LH to v1.4.2

### PR DESCRIPTION
**Pull request by guangbochen**
**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

**Problem:**
- Need to cherry-pick the upstream kubevirt fix:
  - https://github.com/kubevirt/kubevirt/pull/8914
  - https://github.com/kubevirt/kubevirt/pull/9269
- Need to bump Longhorn to v1.4.2 to include some upstream fixes

**Solution:**
- Patch the kubevirt image from SUSE SLEs
- Bump Longhorn go mod and dependency chart to the v1.4.2 release

**Related Issue:**
- https://github.com/harvester/harvester/issues/3747

  **longhorn related:**
  - https://github.com/harvester/harvester/issues/3315
  - https://github.com/harvester/harvester/issues/3730
  - https://github.com/harvester/harvester/issues/2640
  - https://github.com/harvester/harvester/issues/3123
  - https://github.com/harvester/harvester/issues/1947
  
  **kubevirt related:**
  - https://github.com/harvester/harvester/issues/3586
  - https://github.com/harvester/harvester/issues/1289

**Test plan:**
- build a new ISO image based on the current PR
- verify all pods are running correctly on the `longhorn-system` namespace
- verify all the kubevirt pods are running correctly on the `harvester-system` namespace
- create a VM and check that LH-related features are working as expected. (e.g., snapshot, backup and volumes)

### CODE REVIEW

**Comment by futuretea** [comment]
found another issue in master branch: https://github.com/harvester/harvester/issues/3917 when I test this PR. 
This PR's test plan will be blocked by it. 
after testing, using v1beta2 longhorn client to mount longhorn volume can fix the issue https://github.com/harvester/harvester/issues/3917

**Comment by guangbochen** [comment]
Bumped the Longhorn client to `v1beta2` and it is backward compatible, have tested basic features like VM snapshot, VM backup and volume snapshot, PTAL of the PR again thanks.

**Review by futuretea — APPROVED** [review]
LGTM, Thanks. Test Plan Passed. 
- [x] New Cluster
- [x] Upgrade from v1.1.2
```bash
❯ kubectl -n longhorn-system get po -o custom-columns='NAME:metadata.name,IMAGES:spec.containers[*].image,STATUS:status.phase'
NAME                                                  IMAGES                                                                                                           STATUS
backing-image-manager-144f-fd79                       longhornio/backing-image-manager:v1.4.2                                                                          Running
csi-attacher-6b49484dfd-9wp5d                         longhornio/csi-attacher:v3.4.0                                                                                   Running
csi-attacher-6b49484dfd-kbtcc                         longhornio/csi-attacher:v3.4.0                                                                                   Running
csi-attacher-6b49484dfd-qc5kd                         longhornio/csi-attacher:v3.4.0                                                                                   Running
csi-provisioner-68d95fd6d7-55nbc                      longhornio/csi-provisioner:v2.1.2                                                                                Running
csi-provisioner-68d95fd6d7-7wgcz                      longhornio/csi-provisioner:v2.1.2                                                                                Running
csi-provisioner-68d95fd6d7-jbzc5                      longhornio/csi-provisioner:v2.1.2                                                                                Running
csi-resizer-574496744-bmnvl                           longhornio/csi-resizer:v1.3.0                                                                                    Running
csi-resizer-574496744-jdr6v                           longhornio/csi-resizer:v1.3.0                                                                                    Running
csi-resizer-574496744-nvlxz                           longhornio/csi-resizer:v1.3.0                                                                                    Running
csi-snapshotter-8544bb96b9-4t9wj                      longhornio/csi-snapshotter:v5.0.1                                                                                Running
csi-snapshotter-8544bb96b9-cm89r                      longhornio/csi-snapshotter:v5.0.1                                                                                Running
csi-snapshotter-8544bb96b9-pmfch                      longhornio/csi-snapshotter:v5.0.1                                                                                Running
engine-image-ei-f9e7c473-95smg                        longhornio/longhorn-engine:v1.4.2                                                                                Running
instance-manager-e-e716c9c7889f7e41f1474463d9e3d611   longhornio/longhorn-instance-manager:v1.4.2                                                                      Running
instance-manager-r-e716c9c7889f7e41f1474463d9e3d611   longhornio/longhorn-instance-manager:v1.4.2                                                                      Running
longhorn-admission-webhook-989f468c5-wb656            longhornio/longhorn-manager:v1.4.2                                                                               Running
longhorn-admission-webhook-989f468c5-zkg4p            longhornio/longhorn-manager:v1.4.2                                                                               Running
longhorn-conversion-webhook-66775c66fd-76wb4          longhornio/longhorn-manager:v1.4.2                                                                               Running
longhorn-conversion-webhook-66775c66fd-std5x          longhornio/longhorn-manager:v1.4.2                                                                               Running
longhorn-csi-plugin-vvdds                             longhornio/csi-node-driver-registrar:v2.5.0,longhornio/livenessprobe:v2.8.0,longhornio/longhorn-manager:v1.4.2   Running
longhorn-driver-deployer-65cf79dcd4-kx5z6             longhornio/longhorn-manager:v1.4.2                                                                               Running
longhorn-loop-device-cleaner-8tcj7                    registry.suse.com/bci/bci-base:15.4                                                                              Running
longhorn-manager-ctcld                                longhornio/longhorn-manager:v1.4.2                                                                               Running
longhorn-recovery-backend-7488c69795-7s4tm            longhornio/longhorn-manager:v1.4.2                                                                               Running
longhorn-recovery-backend-7488c69795-f2k58            longhornio/longhorn-manager:v1.4.2                                                                               Running
longhorn-ui-5b9c58656c-hlskm                          longhornio/longhorn-ui:v1.4.2                                                                                    Running
longhorn-ui-5b9c58656c-j6kd7                          longhornio/longhorn-ui:v1.4.2                                                                                    Running
```
```bash
❯ kubectl -n harvester-system get po -o custom-columns='NAME:metadata.name,IMAGES:spec.containers[*].image,STATUS:status.phase'
NAME                                                    IMAGES                                                                  STATUS
harvester-d6bcf6bf8-s7g55                               harbor.futuretea.me/rancher/harvester:pr-3910-head                      Running
harvester-load-balancer-78f7f798bf-4r7n7                rancher/harvester-load-balancer:master-head                             Running
harvester-network-controller-manager-696cc7dd85-z5sqv   rancher/harvester-network-controller:master-head                        Running
harvester-network-controller-vtp4l                      rancher/harvester-network-controller:master-head                        Running
harvester-network-webhook-b5b67774b-2pc9r               rancher/harvester-network-webhook:master-head                           Running
harvester-node-disk-manager-wwh6r                       rancher/harvester-node-disk-manager:master-head                         Running
harvester-node-manager-vbp8s                            rancher/harvester-node-manager:master-head                              Running
harvester-publicmgmt-vlan1-8b31f70a-wrt54               rancher/harvester-network-helper:master-head                            Succeeded
harvester-webhook-77dc6777bd-868sg                      harbor.futuretea.me/rancher/harvester-webhook:pr-3910-head              Running
kube-vip-cloud-provider-0                               kubevip/kube-vip-cloud-provider:v0.0.1                                  Running
kube-vip-hj6wk                                          ghcr.io/kube-vip/kube-vip:v0.5.12                                       Running
virt-api-5dbb96df9d-2xvgz                               registry.suse.com/suse/sles/15.4/virt-api:0.54.0-150400.3.16.1          Running
virt-controller-cc64b84b8-9p2wj                         registry.suse.com/suse/sles/15.4/virt-controller:0.54.0-150400.3.16.1   Running
virt-controller-cc64b84b8-px6dk                         registry.suse.com/suse/sles/15.4/virt-controller:0.54.0-150400.3.16.1   Running
virt-handler-896th                                      registry.suse.com/suse/sles/15.4/virt-handler:0.54.0-150400.3.16.1      Running
virt-operator-6459668bd5-slshb                          registry.suse.com/suse/sles/15.4/virt-operator:0.54.0-150400.3.16.1     Running
```

**Review by Vicente-Cheng — APPROVED** [review]
Tested with VM creation/migration/snapshot and basic volume operations.
Looks fine, thanks!

**Review by bk201 — APPROVED** [review]
lgtm! The kubevirt bump also solves https://github.com/harvester/harvester-installer/pull/491#issuecomment-1551081731

**Pull request merged**
