### PR TITLE
Bump: LH to v1.7.0-rc3

### PR DESCRIPTION
**Pull request by Yu-Jack**
https://github.com/harvester/harvester/issues/6172

### CODE REVIEW

**Review by FrankYang0529 — APPROVED** [review]

**Review by bk201 — APPROVED** [review]

**Comment by bk201** [comment]
@Yu-Jack Please help remove the unchanged chart tarballs charts.

**Comment by Yu-Jack** [comment]
@bk201 Done.

**Review by bk201 — APPROVED** [review]

**Review by Vicente-Cheng — APPROVED** [review]
LGTM, verified with basic volume operations.

**Comment by Vicente-Cheng** [comment]
@mergify backport v1.4

**Pull request merged**
