### PR TITLE
check CDROM and container disk before VM migration

### PR DESCRIPTION
**Pull request by w13915984028**
**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

**Problem:**

CD-ROM type of volume should block the migration and pop proper error message

Container Disk type of volume should block the migration and pop proper error message

**Solution:**

check the volumes of vmi before migration

**Related Issue:**
https://github.com/harvester/harvester/issues/2641
https://github.com/harvester/harvester/issues/3429

**Test plan:**

Add CD-ROM, Container-disk to VM
The "migrate" action failed with proper error message.
Remove CD-ROM, Conainer-disk from VM, "migrate" is allowed.

Error message when migrating VM
image

doc PR: https://github.com/harvester/docs/pull/284

### CODE REVIEW

**Comment by bk201** [comment]
It would be nice to check container disks as well: https://github.com/harvester/harvester/issues/3429
Is it possible to do the check in the admission webhook?

**Comment by w13915984028** [comment]
@bk201 

> It would be nice to check container disks as well: #3429 

Added

> Is it possible to do the check in the admission webhook?

Do you mean `pkg/webhook/resources/virtualmachine/validator.go` ? none of migrate related checks are there
seems under `pkg/webhook,` none function are related to migrate/migration

**Review by FrankYang0529 — APPROVED** [review]
LGTM. Thanks.

**Review by guangbochen — APPROVED** [review]
LGTM, thanks.

**Review by bk201 — APPROVED** [review]
lgtm

**Comment by bk201** [comment]
@mergifyio backport

**Comment by bk201** [comment]
@mergifyio backport v1.1

**Pull request merged**
