### PR TITLE
dep chart for node manager

### PR DESCRIPTION
**Pull request by chrisho**
**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

**Problem:**
The PR introduces the helm chart for node-manager

**Solution:**

**Related Issue:** https://github.com/harvester/harvester/issues/2302

**Test plan:**

### CODE REVIEW

**Review by futuretea — COMMENTED** [review]
missing chart tgz package

**Comment by chrisho** [comment]
> missing chart tgz package

updated

**Review by futuretea — APPROVED** [review]
LGTM

**Review by guangbochen — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
