### PR TITLE
Create template from vm

### PR DESCRIPTION
**Pull request by rmweir**
**Problem:**

Cannot create a template that matches an already existing VM.

**Solution:**

Add an action "createTemplate" that creates a vm template based on the given vm.

**Related Issue:**
https://github.com/rancher/harvester/issues/517

**Test plan:**

### CODE REVIEW

**Review by guangbochen — APPROVED** [review]
LGTM

**Comment by gitlawr** [comment]
LGTM. Can you do a rebase?

**Comment by rmweir** [comment]
@gitlawr done

**Comment by gitlawr** [comment]
Thanks!

**Pull request merged**
