### PR TITLE
drop amd only node selector for whereabouts

### PR DESCRIPTION
**Pull request by ibrokethecloud**
**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

**Problem:**

storage network setup fails on arm hosts since the whereabouts cni is not deployed to the arm hosts.

This is due to the nodeSelector pinning whereabouts to amd64 only hosts.

**Solution:**

The PR drops this node selector allowing the chart to be deployed to arm hosts as well.

**Related Issue:**
https://github.com/harvester/harvester/issues/371#issuecomment-1992017605
**Test plan:**

### CODE REVIEW

**Comment by ibrokethecloud** [comment]
post change the node selector is dropped from whereabouts ds, and it gets scheduled successfully on arm hosts 
image

**Review by bk201 — APPROVED** [review]
lgtm, I can get storage-network working.

**Comment by bk201** [comment]
@mergifyio backport v1.3

**Comment by WebberHuang1118** [comment]
Addition text: 
- This selector was removed before whereabouts:v0.6.2 https://github.com/k8snetworkplumbingwg/whereabouts/pull/329/files#diff-76958c3d346d977697e48bc7f1a6910e3b9f8b1e3e89efa9e76e5cd50372f8d0
- Related PR https://github.com/k8snetworkplumbingwg/whereabouts/pull/329

**Review by WebberHuang1118 — APPROVED** [review]
LGTM, thanks.

Checked with the upgrade path, and Harvester works as expected:
- Building Harvester with v1.2.1
- Enable Storage Network
- Creating VM with mgmt network, and writing some data to VM
- Upgrading to Harvester built from this PR
- Checking `whereabouts` deployed with `ghcr.io/k8snetworkplumbingwg/whereabouts:v0.6.3`
- Checking VM data integrity

**Comment by bk201** [comment]
@mergifyio backport v1.3

**Pull request merged**
