### PR TITLE
filter role to only have access to whitelisted settings

### PR DESCRIPTION
**Pull request by ibrokethecloud**
**IMPORTANT: Please do not create a Pull Request without creating an issue first.**
PR introduces a minor change to the `harvester-authenticated` role to limit access to UI specific settings only.
**Problem:**

**Solution:**

**Related Issue:**

**Test plan:**

### CODE REVIEW

**Review by guangbochen — APPROVED** [review]
LGTM and MCM UI works fine with this change for me, thanks.

**Review by bk201 — APPROVED** [review]
lgtm!

**Review by guangbochen — APPROVED** [review]
LGTM, the clusterrole is patched correctly.
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
  name: harvester-authenticated
rules:
- apiGroups:
  - harvesterhci.io
  resourceNames:
  - server-version
  - default-storage-class
  - harvester-csi-ccm-versions
  - default-vm-termination-grace-period-seconds
  resources:
  - settings
  verbs:
  - get
  - watch
- apiGroups:
  - network.harvesterhci.io
  resources:
  - clusternetworks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resourceNames:
  - harvester-public
  resources:
  - namespaces
  verbs:
  - get
  - watch

```

**Comment by guangbochen** [comment]
@mergify backport v1.2

**Pull request merged**
