### PR TITLE
Bump SLE BCI image to 15.4

### PR DESCRIPTION
**Pull request by masteryyh**
**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

**Problem:**
Harvester components base image needs to update.

**Solution:**

Upgrade base image from SLE BCI 15.3 to 15.4

**Related Issue:**
[#3149](https://github.com/harvester/harvester/issues/3149)

### CODE REVIEW

**Comment by bk201** [comment]
@starbops Please help check the upgrade image! Thanks!

**Comment by bk201** [comment]
Need to backport to v1.1 branch as well. Thanks!

**Review by starbops — APPROVED** [review]
Tested upgrade from v1.1.1 and then from the same ISO again. Both end with success. LGTM, thanks!

**Review by bk201 — APPROVED** [review]
LGTM, please help squash. Thank you!

**Pull request merged**
