### PR TITLE
Fix upgrade VMI status detection

### PR DESCRIPTION
**Pull request by w13915984028**
**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

**Problem:**

The VM status detection feature breaks when  2+ VMs are deployed on a specific node

**Solution:**

Fix the VM status detection

**Related Issue:**
https://github.com/harvester/harvester/issues/5008

**Test plan:**

1. create 2+ VMs to deploy on a specific node, then upgrade

2. meanwhile, you can validate the feature locally

```
cat > testvmi.sh << 'EOF'
# return the running VM count
# if `kubectl get vmi` failed, then return "failed to get" for troubleshooting
get_running_vm_count()
{
  local vmioutput=/tmp/vmioutput.yaml
  rm -f "$vmioutput"
  local EXIT_CODE=0

  kubectl get vmi -A -l kubevirt.io/nodeName=$HARVESTER_UPGRADE_NODE_NAME -o yaml > "$vmioutput" || EXIT_CODE=$?

  if [[ "$EXIT_CODE" -eq 0 ]]; then
    local count=$(yq e '.items |  map(select(.status.phase!="Succeeded")) | length' "$vmioutput")
    echo "$count"
  else
    echo "failed to get"
  fi
  rm -f "$vmioutput"
}

wait_vms_out_or_shutdown()
{
  local vm_count

  while [ true ]; do
    vm_count="$(get_running_vm_count)"

    if [ "$vm_count" = "0" ]; then
      break
    fi

    echo "Waiting for VM live-migration or shutdown...(count: $vm_count)"
    sleep 5
  done
  echo "all VMs on node $HARVESTER_UPGRADE_NODE_NAME have been live-migrated or shutdown"
}


export HARVESTER_UPGRADE_NODE_NAME=harv41


wait_vms_out_or_shutdown
EOF
chmod +x ./testvmi.sh
./testvmi.sh
```

when the script is running, you can start/stop VMs to observe

```
$ ./testvmi.sh
Waiting for VM live-migration or shutdown...(count: 2)
Waiting for VM live-migration or shutdown...(count: 2)
Waiting for VM live-migration or shutdown...(count: 1)
Waiting for VM live-migration or shutdown...(count: 1)
all VMs on node harv41 have been live-migrated or shutdown
```

error test case: (e.g. a non-existing resource vmii)

```
$ ./testvmi.sh
error: the server doesn't have a resource type "vmii"
Waiting for VM live-migration or shutdown...(count: failed to get)
error: the server doesn't have a resource type "vmii"
Waiting for VM live-migration or shutdown...(count: failed to get)
```

### CODE REVIEW

**Comment by w13915984028** [comment]
@Mergifyio backport v1.2 v1.3

**Review by starbops — COMMENTED** [review]
@w13915984028 Thanks for the fix! I wonder if the slightly tweaked version can fix the previous one:

```
kubectl get vmi -A -l kubevirt.io/nodeName=$HARVESTER_UPGRADE_NODE_NAME -o yaml | yq e '.items | map(select(.status.phase!="Succeeded")) | length'
```

**Comment by bk201** [comment]
> @w13915984028 Thanks for the fix! I wonder if the slightly tweaked version can fix the previous one:
> 
> ```
> kubectl get vmi -A -l kubevirt.io/nodeName=$HARVESTER_UPGRADE_NODE_NAME -o yaml | yq e '.items | map(select(.status.phase!="Succeeded")) | length'
> ```

+1, looks straightforward

**Comment by w13915984028** [comment]
> @w13915984028 Thanks for the fix! I wonder if the slightly tweaked version can fix the previous one:
> 
> ```
> kubectl get vmi -A -l kubevirt.io/nodeName=$HARVESTER_UPGRADE_NODE_NAME -o yaml | yq e '.items | map(select(.status.phase!="Succeeded")) | length'
> ```

@starbops 

1. The `map` keyword is cool.

2.  An output yaml is temporarly used.

>count=$(kubectl get vmi -A -l kubevirt.io/nodeName=$HARVESTER_UPGRADE_NODE_NAME -o yaml | yq e '.items |  map(select(.status.phase!="Succeeded")) | length' || true)

if `kubectl get vmii` return error then the `yq` will return 0, this is not wanted

e.g.:
```
count=$(kubectl get vmii -A -l kubevirt.io/nodeName=$HARVESTER_UPGRADE_NODE_NAME -o yaml | yq e '.items |  map(select(.status.phase!="Succeeded")) | length' || true)
error: the server doesn't have a resource type "vmii"
harv41:/home/rancher # echo $?
0
harv41:/home/rancher # echo $count
0
```

**Comment by starbops** [comment]
> if kubectl get vmii return error then the yq will return 0, this is not wanted

Good point.

But using `-f` to check if there is output seems not reliable, see:

```
$ if [ -f tempfile ]; then echo yes; else echo no; fi
no

$ kubectl get vmii > tempfile
error: the server doesn't have a resource type "vmii"

$ if [ -f tempfile ]; then echo yes; else echo no; fi
yes
```

**Review by starbops — APPROVED** [review]
LGTM, thank you!

**Review by bk201 — APPROVED** [review]

**Pull request merged**
