### PR TITLE
Remove definition descriptions and add a summary of each path

### PR DESCRIPTION
**Pull request by chrisho**
**Problem:**
https://github.com/harvester/harvester/issues/4443

**Solution:**
- Remove definition descriptions
- Remove the ObjectMeta unused member, and keep the name and namespace.
- Add a summary of paths

**Related Issue:**
https://github.com/harvester/harvester/issues/4443

**Test plan:**
build the swagger file successfully.

### CODE REVIEW

**Comment by guangbochen** [comment]
This PR introduces the required swagger API doc changes for https://github.com/harvester/docs/pull/388, the preview is available on https://64e887487470e9009a45d6c1--harvester-preview.netlify.app/dev/category/api

**Review by guangbochen — APPROVED** [review]
LGTM, thanks.

**Review by futuretea — APPROVED** [review]
LGTM, thanks.

**Review by bk201 — APPROVED** [review]

**Comment by guangbochen** [comment]
@mergify backport v1.2

**Comment by guangbochen** [comment]
@chrisho you may backport this to v1.1 manually since the API spec would be different in two versions, thanks.

**Pull request merged**
