### PR TITLE
image updates: harvester-upgrade and pre-delete job image

### PR DESCRIPTION
**Pull request by bk201**
image update:
- `rancher/harvester-upgrade`
- Helm chart pre-delete job image: https://github.com/harvester/harvester/blob/1c06027537a7d1ad035501842e4ef3c099ef5dbf/deploy/charts/harvester/values.yaml#L325

### CODE REVIEW

**Review by guangbochen — COMMENTED** [review]
should we backport the changes from https://github.com/harvester/harvester/pull/2580/files, thanks.

**Comment by bk201** [comment]
> should we backport the changes from https://github.com/harvester/harvester/pull/2580/files, thanks.

Sure, thanks for the reminder!

**Review by guangbochen — APPROVED** [review]
LGTM, thanks.

**Review by FrankYang0529 — APPROVED** [review]
LGTM

**Pull request merged**
