### PR TITLE
Bump to LH v1.2.3-rc2

### PR DESCRIPTION
**Pull request by guangbochen**
Bump to LH v1.2.3-rc2

### CODE REVIEW

**Review by gitlawr — APPROVED** [review]
LGTM

**Review by bk201 — CHANGES_REQUESTED** [review]
`build-bundle` fails with:
```
+ for i in "${!repositories[@]}"
+ echo kubevip/kube-vip-cloud-provider:0.1
+ cat
++ ls ../harvester/deploy/charts/harvester/charts
++ grep longhorn
++ sed -e 's/^longhorn-//' -e 's/.tgz$//'
+ longhorn_version='v1.2.3-rc1
1.2.3-rc2'
+ longhorn_image_url='https://raw.githubusercontent.com/longhorn/longhorn/v1.2.3-rc1
1.2.3-rc2/deploy/longhorn-images.txt'
+ curl https://raw.githubusercontent.com/longhorn/longhorn/v1.2.3-rc1 1.2.3-rc2/deploy/longhorn-images.txt
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    20  100    20    0     0     47      0 --:--:-- --:--:-- --:--:--    47
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: 1.2.3-rc2
FATA[0140] exit status 6
make: *** [Makefile:11: dev] Error 1
```

Need to remove the old tarball:
```
╰─$ ls deploy/charts/harvester/charts | grep longhorn
longhorn-1.2.3-rc1.tgz
longhorn-1.2.3-rc2.tgz
```

**Comment by guangbochen** [comment]
Thanks, should be a mistake during code rebase and updated.

**Review by bk201 — APPROVED** [review]
Thanks, it works now.

**Pull request merged**
