### PR TITLE
Bump Kubevirt to 0.45.0

### PR DESCRIPTION
**Pull request by weihanglo**
> ### BLOCKED: wait for the release of SLES-based kubevirt images and then bump helm chart

**Problem:**
Bump KubeVirt to 0.45.0 for hot-unplug support

**Solution:**

1. Bump version (WIP) and helm chart (BLOCKED). 
2. Update for API changes accordingly:
    - [`v1.PersistentVolumeClaimVolumeSource`](https://kubevirt.io/api-reference/v0.45.0/definitions.html#_v1_persistentvolumeclaimvolumesource): new `hotpluggable` field
    - [`v1.DataVolumeSource`](https://kubevirt.io/api-reference/v0.45.0/definitions.html#_v1_datavolumesource): new `hotpluggable` field
    
    By specifying those field to `true`, the volume in a VM turns to be hot-pluggable and  be unplugged at anytime, as well as be reattached after a VM restart.

**Related Issue:**
#283 

**Test plan:**
After this upgrade, we can make a volume in a VM hotpluggable by setting `spec.volumes.persistentvolumeclaim.hotpluggable` to true. There are two things we can test:

1. A hotpluggable volume can be hotunplugged even after restart the VM.
2. A hotpluggable volume will be auto-reattached after a VM restart.

### CODE REVIEW

**Comment by weihanglo** [comment]
Note: This PR does not alter base templates. In theory, we can mark all PVC volumes source as `hotpluggable` including root-disk.

**Comment by guangbochen** [comment]
@weihanglo the SUSE image is available at `registry.suse.com/harvester-beta` and all have the tag `0.45.0`

**Comment by weihanglo** [comment]
Got **"is attempting to grant RBAC permissions not currently held"** in virt-operator's logs for following rules:

```yaml
- apiGroups:
    - subresources.kubevirt.io
  resources:
    - virtualmachineinstances/guestosinfo
    - virtualmachineinstances/filesystemlist
    - virtualmachineinstances/userlist
  verbs:
    - get
```

Since it cannot apply the rules, virt-controller and other components did not finish the installation.

Need to figure out why.

**Comment by guangbochen** [comment]
@weihanglo can u please check if the kubevirt have updated the subresoruce names via `/apis/subresources.kubevirt.io/v1`

**Comment by weihanglo** [comment]
@guangbochen Yep. KubeVirt have already used API group `subresources.kubevirt.io` for a long time:

- https://kubevirt.io/api-reference/v0.45.0/operations.html#_v1guestosinfo
- https://github.com/kubevirt/kubevirt/blob/efcc11c/pkg/virt-api/rest/subresource.go

Does this cause the RBAC permission error?

**Comment by weihanglo** [comment]
May related to [this change](https://git.io/JzuPC). Still investigating.

**Comment by guangbochen** [comment]
Yep, and since there is no official kubevirt chart so we have maintained the chart on our own via https://github.com/harvester/harvester/tree/master/deploy/charts/harvester/dependency_charts/kubevirt-operator, make sure the CRDs and template files are aligned with the new kubevirt releases by comparing its release assets https://github.com/kubevirt/kubevirt/releases/tag/v0.45.0, thanks.

**Comment by weihanglo** [comment]
Close in favor of #1336

**Pull request closed without merging**
