### PR TITLE
fix: add nfs and s3 back to vendor

### PR DESCRIPTION
**Pull request by FrankYang0529**
**Problem:**
NFS and S3 were deleted in vendor, so we got `Driver nfs/s3 is not supported`.

**Solution:**
Add NFS and S3 back to vendor.

**Related Issue:**
https://github.com/harvester/harvester/issues/3464
https://github.com/harvester/harvester/issues/3462

**Test plan:**

* Case 1: Test backup / restore with NFS
* Case 2: Test backup / restore with S3

### CODE REVIEW

**Review by guangbochen — APPROVED** [review]
LGTM, and thanks for the fixing.

**Comment by guangbochen** [comment]
The Trivy CI will be addressed via https://github.com/harvester/harvester/pull/3479 so we can ingore it.

**Review by bk201 — APPROVED** [review]
Thanks for adding more comments to explain why we need the blank imports.

**Comment by FrankYang0529** [comment]
@Mergifyio backport v1.1

**Pull request merged**
