### PR TITLE
Add validator for virtualmachinetemplateversion resources limits

### PR DESCRIPTION
**Pull request by w13915984028**
**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

**Problem:**

The virtualmachinetemplateversion resources limits of CPU and Memory are mandatory fields, but UI does not check them now. The validator makes sure them are existing.

**Solution:**

Add validator tor check.

**Related Issue:**
https://github.com/harvester/harvester/issues/4625

**Test plan:**

Create `Templates` in Harvester UI, per https://github.com/harvester/harvester/issues/4625#issuecomment-1766133397.

### CODE REVIEW

**Review by connorkuehl — COMMENTED** [review]
LGTM, but what do you think of rephrasing the error messages, something like:

`CPU and Memory limits are required fields, but are missing from the input`

`Memory limit is a required field, but is missing from the input`

`CPU limit is a required field, but is missing from the input`

**Review by markhillgit — APPROVED** [review]
This looks good to me, I also think Connor's suggestion about the messages would be a good improvement.

**Review by connorkuehl — APPROVED** [review]

**Comment by bk201** [comment]
@w13915984028 can you check if the drone CI error is relevant, if not I can restart the test.

**Comment by w13915984028** [comment]
@bk201 Checked, the drone CI should be related to others. In previous commit, the CI https://drone-pr.rancher.io/harvester/harvester/3882 is success, in current commit, only the return message is updated.

The direct related messages of CI failure are in below, I will take a look of the CI code later. 
```
  [1mSTEP:[0m when deleting the virtual machine with removeDisks query parameter [38;5;243m@ 10/19/23 08:39:29.597[0m
  [38;5;9m[FAILED][0m in [It] - /go/src/github.com/harvester/harvester/vendor/github.com/onsi/ginkgo/v2/internal/node.go:463 [38;5;243m@ 10/19/23 08:39:29.665[0m
[38;5;9m• [FAILED] [8.138 seconds][0m
[0mverify vm APIs [38;5;243moperate via steve API [38;5;9m[1m[It] deleting a vm and its volume[0m
[38;5;243m/go/src/github.com/harvester/harvester/tests/integration/api/vm_apis_test.go:245[0m

  [38;5;9m[FAILED] failed to delete action, response with 500, {"type":"error","links":{},"code":"ServerError","message":"Failed to set removedPersistentVolumeClaims to virtualMachine default/test-7h4z9, Operation cannot be fulfilled on virtualmachines.kubevirt.io \"test-7h4z9\": the object has been modified; please apply your changes to the latest version and try again","status":500,"type":"error"}
  [0m
```

**Comment by w13915984028** [comment]
Add a new issue https://github.com/harvester/harvester/issues/4637 to enhance.

The Drone CI will fail randomly due to this issue.

Either backend code or CI code should add retry in such cases.

At first, we can enhance CI.

**Review by bk201 — APPROVED** [review]
LGTM, thanks!

**Comment by bk201** [comment]
@mergifyio backport v1.2

**Pull request merged**
