### PR TITLE
Bump: Longhorn to v1.7.0-rc4

### PR DESCRIPTION
**Pull request by Yu-Jack**
**Related Issue:**
https://github.com/harvester/harvester/issues/6172

**Test plan:**

- [x] Verify that VM starting, stoping, restarting and restoring snapshot work.
- [x] In longhorn-csi-plugin container of longhorn-csi-plugin pods, curl http://longhorn-backend:9500/v1 repeatedly should work well (Use following script to test).

```sh
cd /tmp

echo '
#!/bin/bash

# Target URL
URL="http://longhorn-backend:9500/v1"
# Number of attempts
MAX_ATTEMPTS=100

for ((i=1; i<=MAX_ATTEMPTS; i++)); do
    # Send curl request
    RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" $URL)

    # Check if the request was successful (status code 200)
    if [ "$RESPONSE" -ne 200 ]; then
        echo "Error: Failed to reach $URL on attempt $i. HTTP Status Code: $RESPONSE"
    else
        echo "Success: Reached $URL on attempt $i"
    fi

    # Set a wait time if needed (e.g., check every 5 seconds)
done
' > test.sh

sh test.sh
```

### CODE REVIEW

**Comment by bk201** [comment]
The connection from longhorn-csi-plugin pods to longhorn-manager pods looks good. And longhorn-csi-plugin pods are switched back to overlay network IPs.

**Review by bk201 — APPROVED** [review]

**Review by Vicente-Cheng — APPROVED** [review]
LGTM, tested with VM/Volume basic operations.

Also, ensure the longhorn-csi-pod now could connect to longhorn-manager w/o any issues.

The LH RWX volume with storage network also worked as usual.

**Comment by bk201** [comment]
@mergifyio backport v1.4

**Review by WebberHuang1118 — APPROVED** [review]
LGTM, tested the following cases for data integrity under the storage network
- Image
  - Creating from local
  - Creating from URL download
  - Volume exporting
- VM backup/snapshot
  - Taking backup/snapshot during VM is running
  - Taking backup/snapshot during VM is stopped
- VM backup/snapshot restore
  - Restoring to new
  - Restoring to new to another namespace
  - Restoring as replacing existing

**Pull request merged**
