### PR TITLE
Bump longhorn to v1.5.3

### PR DESCRIPTION
**Pull request by FrankYang0529**
**Solution:**
Bump longhorn to v1.5.3

**Related Issue:**
https://github.com/harvester/harvester/issues/5056

**Test plan:**
### Case 1: New cluster

Make sure users can operate creating/migrating VM, creating and restoring VMBackup/VMSnapshot.

### Case 2: Upgrade cluster

1. Create a harvester v1.2.1 cluster.
2. Create a guest cluster.
3. Make sure the harvester can bump to this branch.
4. After the first bump is successful, bump the cluster again to master-head.

When bumping to master-head, the `rancher/harvester-cluster-repo` may not be reloaded, because the tag is same. This issue will not happened in production, because the tag will be different. For testing, users can load it manually after each node is in image-preloaded status. After doing it on each node, users can delete harvester-cluster-repo pod to restart it.

```bash
# the ip is cluster-ip of upgrade-repo-hvst-upgrade-xxx service.
curl -sfL http://<ip>/harvester-iso/bundle//harvester/images/harvester-repo-images-master.tar.zst | zstdcat | ctr -n k8s.io images import -
```

### CODE REVIEW

**Review by Vicente-Cheng — APPROVED** [review]
LGTM, tested with https://github.com/harvester/harvester-installer/pull/646
upgrade path from v1.2.1 -> v1.2-head (this PR) -> master-head

verified the VM can be migrated (w/o vlan due to https://github.com/harvester/harvester/issues/5076)
And all basic operations work well.

**Comment by WebberHuang1118** [comment]
Hi @FrankYang0529,
I tested with fundamental operations (including `VM Backup`, `VM Snapshot`, `VM Restore`, `Image creation`, `Image exporting` ... etc) after upgrading to this branch. However, I couldn't progress the second upgrade to the `master-head` branch even after applying the [workarounds](https://github.com/harvester/harvester/pull/5057#issue-2107356331), the upgrade is stuck in the `apply manifest`, any suggestion? Thanks.

Update:
I continued the second upgrade by deleting the `fleet-agent` pod after applying the workaround mentioned in the test plan.

**Review by WebberHuang1118 — APPROVED** [review]
LGTM, thanks.

**Review by markhillgit — APPROVED** [review]
lgtm, thanks

**Review by ibrokethecloud — APPROVED** [review]
lgtm. thanks.

**Pull request merged**
