### PR TITLE
Release v1.1.1-rc1

### PR DESCRIPTION
**Pull request by bk201**
Version changes:
- UI: v1.1.1-rc1
- Installer: v1.1.1-rc1
- Upgrade matrix: minimum v1.0.3

### CODE REVIEW

**Comment by futuretea** [comment]
Fix the CI error in https://github.com/harvester/harvester/pull/3131

**Review by guangbochen — APPROVED** [review]
LGTM, thanks.

**Review by Vicente-Cheng — APPROVED** [review]
test with the upgrade path.
All VMs look good and basic operations also work well.

LGTM, thanks!

**Review by futuretea — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
