### PR TITLE
feat: Upgrade `cluster.x-k8s.io/v1alpha4` to `cluster.x-k8s.io/v1beta1`

### PR DESCRIPTION
**Pull request by FrankYang0529**
**Problem:**
The `cluster.x-k8s.io/v1alpha4` will be removed after v1.6. Currently, we use CAPI v1.4.4. We only have 1 minor version to upgrade it.

ref: https://cluster-api.sigs.k8s.io/#-breaking-changes-

**Solution:**
Upgrade `cluster.x-k8s.io/v1alpha4` to `cluster.x-k8s.io/v1beta1`.

**Related Issue:**
https://github.com/harvester/harvester/issues/5268

**Test plan:**
Use the branch to create a 3-node harvester cluster. Check following command can return 3 machines.

```
> kubectl get machine -l cluster.x-k8s.io/control-plane="true" -n fleet-local
NAME                  CLUSTER   NODENAME           PROVIDERID                PHASE     AGE   VERSION
custom-8d55f0c99604   local     harvester-node-1   rke2://harvester-node-1   Running   22m
custom-a3955af0bcd0   local     harvester-node-0   rke2://harvester-node-0   Running   26m
custom-f05377afb1b1   local     harvester-node-2   rke2://harvester-node-2   Running   15m
```

### CODE REVIEW

**Review by brandboat — APPROVED** [review]
LGTM 
Now the annoying log `cluster.x-k8s.io/v1alpha4 Machine is deprecated; use cluster.x-k8s.io/v1beta1 Machine` no longer exist in harvester deployment log ! :partying_face:

**Review by Yu-Jack — APPROVED** [review]
LGTM, thanks!

**Review by bk201 — APPROVED** [review]
Thanks for fixing this.

**Review by ibrokethecloud — APPROVED** [review]
lgtm. thanks.

**Pull request merged**
