### PR TITLE
fix: Harvester ManagedChart is modified after an upgrade

### PR DESCRIPTION
**Pull request by bk201**
Ignore the status fields in some post-modified CRDs in the upgrade path.

**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

**Problem:**

**Solution:**

**Related Issue:**

**Test plan:**

### CODE REVIEW

**Review by Vicente-Cheng — APPROVED** [review]
Thanks for fixing that!

**Comment by w13915984028** [comment]
A question here: the `ComparePatches` is defined as an array. The multi run of current code will expand the array. Should we check if the target value is not in the array and then append it?

```
type DiffOptions struct {
	ComparePatches []ComparePatch `json:"comparePatches,omitempty"`
}

type ComparePatch struct {
	Kind         string      `json:"kind,omitempty"`
	APIVersion   string      `json:"apiVersion,omitempty"`
	Namespace    string      `json:"namespace,omitempty"`
	Name         string      `json:"name,omitempty"`
	Operations   []Operation `json:"operations,omitempty"`
	JsonPointers []string    `json:"jsonPointers,omitempty"`
}
```

**Comment by bk201** [comment]
> A question here: the `ComparePatches` is defined as an array. The multi run of current code will expand the array. Should we check if the target value is not in the array and then append it?
> 

Good point, updated. The script is now idempotent. I'd keep the v1.2.1 one since it's already shipped.

**Comment by bk201** [comment]
@mergifyio backport v1.3

**Review by Vicente-Cheng — APPROVED** [review]
LGTM, tested the upgrade from v1.3.0 to v1.3-head.

Works well.

**Review by starbops — APPROVED** [review]
Tested with upgrade from v1.3.0 to master containing this fix. LGTM, thank you.

**Pull request merged**
