### PR TITLE
fix(image): delete and create race condition

### PR DESCRIPTION
**Pull request by FrankYang0529**
**Problem:**
We didn't set `OwnerReference` in BackingImage, so VMImage can be deleted when BackingImage is in deleting progress. At this time, if we create another VMImage with the same name, it may get a BackingImage with `DeletionTimestamp`. Because the status of the BackingImage is good, we don't process the VMImage. Finally, we may get a VMImage with 0% progress on the dashboard ([ref](https://github.com/harvester/harvester/issues/3773#issuecomment-1508253405)). 

**Solution:**
If the BackingImage has `DeletionTimestamp`, we enqueue the VMImage again.

**Related Issue:**
https://github.com/harvester/harvester/issues/3773

**Test plan:**

We can not manually reproduce the issue, because the time gap is too small. We can run [harvester/tests](https://github.com/harvester/tests) to check it.

```sh
tox -e py38 -- harvester_e2e_tests --html=test_result.html -s -vv -k 'test_vm.py'
```

### CODE REVIEW

**Comment by WebberHuang1118** [comment]
Hi Frank,

I'm wondering about certain cases, that may still get VMImages stuck under current solution.

Assuming the following circumstance:
1. A VMImage `image-abc` is created, and a BackingImage `default-image-abc` is also created along with it (for example from the VMImage file upload operation)
2. VMImage `image-abc` is deleted, and a deletion request is issued for BackingImage `default-image-abc`
3. Since the deletion for BackingImage `default-image-abc` isn't atomic, it could go through three phases in order
        a. The `DeletionTimestamp` field is null
        b. The `DeletionTimestamp` field is set
        c. BackingImage `default-image-abc` destroyed
4. If during BackingImage `default-image-abc` is in phase (a), a new VMImage `image-abc` is created with the same name, it would pass the checking about BackingImage
5. The BackingImage `default-image-abc` complete reamining phase (b) and (c), and be deleted finally
6. Since BackingImage `default-image-abc` no longer exists, the new VMImage `image-abc` may still go stuck

Is this possible to happen ? Need your comment on it

thanks,
Webber

**Comment by FrankYang0529** [comment]
> 1. A VMImage `image-abc` is created, and a BackingImage `default-image-abc` is also created along with it (for example from the VMImage file upload operation)
> 2. VMImage `image-abc` is deleted, and a deletion request is issued for BackingImage `default-image-abc`
> 3. Since the deletion for BackingImage `default-image-abc` isn't atomic, it could go through three phases in order
>    a. The `DeletionTimestamp` field is null
>    b. The `DeletionTimestamp` field is set
>    c. BackingImage `default-image-abc` destroyed
> 4. If during BackingImage `default-image-abc` is in phase (a), a new VMImage `image-abc` is created with the same name, it would pass the checking about BackingImage
> 5. The BackingImage `default-image-abc` complete reamining phase (b) and (c), and be deleted finally
> 6. Since BackingImage `default-image-abc` no longer exists, the new VMImage `image-abc` may still go stuck
> 
> Is this possible to happen ? Need your comment on it

We have a [OnRemove](https://github.com/harvester/harvester/blob/8413da412fbfa0431c92d25f6c5a68ab35ac295b/pkg/controller/master/image/vm_image_controller.go#L87) function for VMImage. It adds a finalizer to VMImage. From [k8s finalizer document](https://kubernetes.io/docs/concepts/overview/working-with-objects/finalizers/):
> An object remains in a terminating state while controllers take the actions defined by the finalizers. After these actions are complete, the controller removes the relevant finalizers from the target object. When the `metadata.finalizers` field is empty, Kubernetes considers the deletion complete and deletes the object.

Based on the document, we will not have a situation that the VMImage is deleted and BackingImage's `DeletionTimestamp` is null.

**Review by WebberHuang1118 — APPROVED** [review]
LGTM, thanks

**Review by bk201 — APPROVED** [review]
LGTM!

**Review by guangbochen — APPROVED** [review]
LGTM, thanks.

**Comment by guangbochen** [comment]
@mergify backport v1.1

**Pull request merged**
