### PR TITLE
Bump harvester network controller 0.3.3

### PR DESCRIPTION
**Pull request by yaocw2020**
**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

**Problem:**

We kept the deprecated CRD nodenetworks for upgrading from Harvester v1.0.2 to v1.1.0 before. Because it's not used anymore from Harvester v1.2.0, remove it in the Harvester network controller 0.3.3.

**Solution:**

**Related Issue:**

**Test plan:**

### CODE REVIEW

**Comment by guangbochen** [comment]
@yaocw2020 u may need to include https://github.com/harvester/charts/pull/171 in the new network-controller chart, thanks.

**Comment by yaocw2020** [comment]
> @yaocw2020 u may need to include [harvester/charts#171](https://github.com/harvester/charts/pull/171) in the new network-controller chart, thanks.

Let's delete the harvester network controller chart 0.3.3 in the release and merge the PR. The chart will be generated again. I have tested it.

**Review by guangbochen — APPROVED** [review]
LGTM, thanks.

**Review by bk201 — APPROVED** [review]

**Comment by connorkuehl** [comment]
:thinking: I wonder if I did harvester/charts#171 incorrectly because it looks like beta.kubernetes.io/os is still being rendered after merging this PR:

```console
~/src/harvester/deploy/charts/harvester$ tar xzf ./charts/harvester-network-controller-0.3.3.tgz 

~/src/harvester/deploy/charts/harvester$ grep -R beta\.kubernetes\.io\/os harvester-network-controller
harvester-network-controller/values.yaml:            - key: beta.kubernetes.io/os
```

**Comment by yaocw2020** [comment]
> 🤔 I wonder if I did [harvester/charts#171](https://github.com/harvester/charts/pull/171) incorrectly because it looks like beta.kubernetes.io/os is still being rendered after merging this PR:
> 
> ```
> ~/src/harvester/deploy/charts/harvester$ tar xzf ./charts/harvester-network-controller-0.3.3.tgz 
> 
> ~/src/harvester/deploy/charts/harvester$ grep -R beta\.kubernetes\.io\/os harvester-network-controller
> harvester-network-controller/values.yaml:            - key: beta.kubernetes.io/os
> ```
I checked the new chart harvester-network-controller-0.3.3.tgz generated after PR 171 merged and confirm it's been deleted.

**Pull request merged**
