### PR TITLE
Remove unused monitoring and logging addon upgrade file

### PR DESCRIPTION
**Pull request by w13915984028**
**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

**Problem:**

Those 2 files are redundant, the monitoring and logging upgrade are done in upgrade script instead of directly version bumping.

**Solution:**

Remove thse files.

**Related Issue:**
https://github.com/harvester/harvester/issues/4937

**Test plan:**

Additional: https://github.com/harvester/harvester-installer/pull/750

This PR will erase the warning message in the above PR

```
upgrade addon: rancher-logging version: 102.0.0+up3.17.10
WARNING upgrade addon rancher-logging has version mis-matching: in repo is 103.0.0+up3.17.10 but in addon is 102.0.0+up3.17.10
upgrade addon: rancher-monitoring version: 100.1.0+up19.0.3
WARNING upgrade addon rancher-monitoring has version mis-matching: in repo is 103.0.3+up45.31.1 but in addon is 100.1.0+up19.0.3
```

### CODE REVIEW

**Comment by brandboat** [comment]
Does that mean we could also remove the `convert_logging_audit_to_addon` and `convert_monitoring_to_addon` in `upgrade_manifests.sh` ?

**Comment by w13915984028** [comment]
Will be outdated by https://github.com/harvester/harvester/pull/5633

**Comment by bk201** [comment]
> Will be outdated by #5633

@w13915984028 Do we still need this PR?

**Comment by w13915984028** [comment]
Outdated by https://github.com/harvester/harvester/pull/5633

**Pull request closed without merging**
